// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface AddConnectionEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.AddConnectionEdit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Namespace FQN receiving the usage; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * Namespace FQN receiving the usage; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Usage kind: SysML connection, interface, allocation, binding, flow,
   * succession or transition; KerML connector, binding, flow or succession.
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <pre>
   * Usage kind: SysML connection, interface, allocation, binding, flow,
   * succession or transition; KerML connector, binding, flow or succession.
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <pre>
   * First feature reference resolved from the owner.
   * </pre>
   *
   * <code>string from_end = 3 [json_name = "fromEnd"];</code>
   * @return The fromEnd.
   */
  java.lang.String getFromEnd();
  /**
   * <pre>
   * First feature reference resolved from the owner.
   * </pre>
   *
   * <code>string from_end = 3 [json_name = "fromEnd"];</code>
   * @return The bytes for fromEnd.
   */
  com.google.protobuf.ByteString
      getFromEndBytes();

  /**
   * <pre>
   * Second feature reference resolved from the owner.
   * </pre>
   *
   * <code>string to_end = 4 [json_name = "toEnd"];</code>
   * @return The toEnd.
   */
  java.lang.String getToEnd();
  /**
   * <pre>
   * Second feature reference resolved from the owner.
   * </pre>
   *
   * <code>string to_end = 4 [json_name = "toEnd"];</code>
   * @return The bytes for toEnd.
   */
  com.google.protobuf.ByteString
      getToEndBytes();

  /**
   * <pre>
   * Optional declared name.
   * </pre>
   *
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Optional declared name.
   * </pre>
   *
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional typing target, legal only for typed connection kinds.
   * </pre>
   *
   * <code>string type = 6 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Optional typing target, legal only for typed connection kinds.
   * </pre>
   *
   * <code>string type = 6 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
