// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface AddMemberEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.AddMemberEdit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Namespace FQN to receive the declaration; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * Namespace FQN to receive the declaration; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Written declaration kind, such as "part def" or "class".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <pre>
   * Written declaration kind, such as "part def" or "class".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <pre>
   * Declared identifier.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Declared identifier.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional type target for a usage, written as notation.
   * </pre>
   *
   * <code>string type = 4 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Optional type target for a usage, written as notation.
   * </pre>
   *
   * <code>string type = 4 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * Optional multiplicity, including brackets, such as "[0..*]".
   * </pre>
   *
   * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
   * @return The multiplicity.
   */
  java.lang.String getMultiplicity();
  /**
   * <pre>
   * Optional multiplicity, including brackets, such as "[0..*]".
   * </pre>
   *
   * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
   * @return The bytes for multiplicity.
   */
  com.google.protobuf.ByteString
      getMultiplicityBytes();

  /**
   * <pre>
   * Optional value expression, written as notation.
   * </pre>
   *
   * <code>string value = 6 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Optional value expression, written as notation.
   * </pre>
   *
   * <code>string value = 6 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @return A list containing the specializes.
   */
  java.util.List<java.lang.String>
      getSpecializesList();
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @return The count of specializes.
   */
  int getSpecializesCount();
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @param index The index of the element to return.
   * @return The specializes at the given index.
   */
  java.lang.String getSpecializes(int index);
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the specializes at the given index.
   */
  com.google.protobuf.ByteString
      getSpecializesBytes(int index);

  /**
   * <pre>
   * Whether the declaration is abstract.
   * </pre>
   *
   * <code>bool is_abstract = 8 [json_name = "isAbstract"];</code>
   * @return The isAbstract.
   */
  boolean getIsAbstract();

  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @return A list containing the redefines.
   */
  java.util.List<java.lang.String>
      getRedefinesList();
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @return The count of redefines.
   */
  int getRedefinesCount();
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @param index The index of the element to return.
   * @return The redefines at the given index.
   */
  java.lang.String getRedefines(int index);
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the redefines at the given index.
   */
  com.google.protobuf.ByteString
      getRedefinesBytes(int index);

  /**
   * <pre>
   * Whether the value uses the default assignment keyword.
   * </pre>
   *
   * <code>bool is_default = 10 [json_name = "isDefault"];</code>
   * @return The isDefault.
   */
  boolean getIsDefault();

  /**
   * <pre>
   * Optional usage direction: "in", "out" or "inout".
   * </pre>
   *
   * <code>string direction = 11 [json_name = "direction"];</code>
   * @return The direction.
   */
  java.lang.String getDirection();
  /**
   * <pre>
   * Optional usage direction: "in", "out" or "inout".
   * </pre>
   *
   * <code>string direction = 11 [json_name = "direction"];</code>
   * @return The bytes for direction.
   */
  com.google.protobuf.ByteString
      getDirectionBytes();
}
