// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * AddMemberEdit inserts a declaration into a namespace or the document root.
 * </pre>
 *
 * Protobuf type {@code sysml.AddMemberEdit}
 */
@com.google.protobuf.Generated
public final class AddMemberEdit extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.AddMemberEdit)
    AddMemberEditOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AddMemberEdit");
  }
  // Use AddMemberEdit.newBuilder() to construct.
  private AddMemberEdit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddMemberEdit() {
    owner_ = "";
    kind_ = "";
    name_ = "";
    type_ = "";
    multiplicity_ = "";
    value_ = "";
    specializes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    redefines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    direction_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddMemberEdit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddMemberEdit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.AddMemberEdit.class, org.openmbee.opensysml.proto.AddMemberEdit.Builder.class);
  }

  public static final int OWNER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object owner_ = "";
  /**
   * <pre>
   * Namespace FQN to receive the declaration; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  @java.lang.Override
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Namespace FQN to receive the declaration; empty means the document root.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KIND_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kind_ = "";
  /**
   * <pre>
   * Written declaration kind, such as "part def" or "class".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The kind.
   */
  @java.lang.Override
  public java.lang.String getKind() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kind_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Written declaration kind, such as "part def" or "class".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKindBytes() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Declared identifier.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Declared identifier.
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * Optional type target for a usage, written as notation.
   * </pre>
   *
   * <code>string type = 4 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional type target for a usage, written as notation.
   * </pre>
   *
   * <code>string type = 4 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MULTIPLICITY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object multiplicity_ = "";
  /**
   * <pre>
   * Optional multiplicity, including brackets, such as "[0..*]".
   * </pre>
   *
   * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
   * @return The multiplicity.
   */
  @java.lang.Override
  public java.lang.String getMultiplicity() {
    java.lang.Object ref = multiplicity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      multiplicity_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional multiplicity, including brackets, such as "[0..*]".
   * </pre>
   *
   * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
   * @return The bytes for multiplicity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMultiplicityBytes() {
    java.lang.Object ref = multiplicity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      multiplicity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object value_ = "";
  /**
   * <pre>
   * Optional value expression, written as notation.
   * </pre>
   *
   * <code>string value = 6 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional value expression, written as notation.
   * </pre>
   *
   * <code>string value = 6 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPECIALIZES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList specializes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @return A list containing the specializes.
   */
  public com.google.protobuf.ProtocolStringList
      getSpecializesList() {
    return specializes_;
  }
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @return The count of specializes.
   */
  public int getSpecializesCount() {
    return specializes_.size();
  }
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @param index The index of the element to return.
   * @return The specializes at the given index.
   */
  public java.lang.String getSpecializes(int index) {
    return specializes_.get(index);
  }
  /**
   * <pre>
   * Optional specialization targets for a definition.
   * </pre>
   *
   * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the specializes at the given index.
   */
  public com.google.protobuf.ByteString
      getSpecializesBytes(int index) {
    return specializes_.getByteString(index);
  }

  public static final int IS_ABSTRACT_FIELD_NUMBER = 8;
  private boolean isAbstract_ = false;
  /**
   * <pre>
   * Whether the declaration is abstract.
   * </pre>
   *
   * <code>bool is_abstract = 8 [json_name = "isAbstract"];</code>
   * @return The isAbstract.
   */
  @java.lang.Override
  public boolean getIsAbstract() {
    return isAbstract_;
  }

  public static final int REDEFINES_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList redefines_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @return A list containing the redefines.
   */
  public com.google.protobuf.ProtocolStringList
      getRedefinesList() {
    return redefines_;
  }
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @return The count of redefines.
   */
  public int getRedefinesCount() {
    return redefines_.size();
  }
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @param index The index of the element to return.
   * @return The redefines at the given index.
   */
  public java.lang.String getRedefines(int index) {
    return redefines_.get(index);
  }
  /**
   * <pre>
   * Optional redefinition targets for a usage.
   * </pre>
   *
   * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the redefines at the given index.
   */
  public com.google.protobuf.ByteString
      getRedefinesBytes(int index) {
    return redefines_.getByteString(index);
  }

  public static final int IS_DEFAULT_FIELD_NUMBER = 10;
  private boolean isDefault_ = false;
  /**
   * <pre>
   * Whether the value uses the default assignment keyword.
   * </pre>
   *
   * <code>bool is_default = 10 [json_name = "isDefault"];</code>
   * @return The isDefault.
   */
  @java.lang.Override
  public boolean getIsDefault() {
    return isDefault_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object direction_ = "";
  /**
   * <pre>
   * Optional usage direction: "in", "out" or "inout".
   * </pre>
   *
   * <code>string direction = 11 [json_name = "direction"];</code>
   * @return The direction.
   */
  @java.lang.Override
  public java.lang.String getDirection() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      direction_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional usage direction: "in", "out" or "inout".
   * </pre>
   *
   * <code>string direction = 11 [json_name = "direction"];</code>
   * @return The bytes for direction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDirectionBytes() {
    java.lang.Object ref = direction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      direction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kind_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(multiplicity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, multiplicity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, value_);
    }
    for (int i = 0; i < specializes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, specializes_.getRaw(i));
    }
    if (isAbstract_ != false) {
      output.writeBool(8, isAbstract_);
    }
    for (int i = 0; i < redefines_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, redefines_.getRaw(i));
    }
    if (isDefault_ != false) {
      output.writeBool(10, isDefault_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(direction_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, direction_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kind_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(multiplicity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, multiplicity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, value_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < specializes_.size(); i++) {
        dataSize += computeStringSizeNoTag(specializes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSpecializesList().size();
    }
    if (isAbstract_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isAbstract_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < redefines_.size(); i++) {
        dataSize += computeStringSizeNoTag(redefines_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRedefinesList().size();
    }
    if (isDefault_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isDefault_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(direction_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, direction_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.AddMemberEdit)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.AddMemberEdit other = (org.openmbee.opensysml.proto.AddMemberEdit) obj;

    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (!getKind()
        .equals(other.getKind())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getMultiplicity()
        .equals(other.getMultiplicity())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getSpecializesList()
        .equals(other.getSpecializesList())) return false;
    if (getIsAbstract()
        != other.getIsAbstract()) return false;
    if (!getRedefinesList()
        .equals(other.getRedefinesList())) return false;
    if (getIsDefault()
        != other.getIsDefault()) return false;
    if (!getDirection()
        .equals(other.getDirection())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + getKind().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + MULTIPLICITY_FIELD_NUMBER;
    hash = (53 * hash) + getMultiplicity().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    if (getSpecializesCount() > 0) {
      hash = (37 * hash) + SPECIALIZES_FIELD_NUMBER;
      hash = (53 * hash) + getSpecializesList().hashCode();
    }
    hash = (37 * hash) + IS_ABSTRACT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAbstract());
    if (getRedefinesCount() > 0) {
      hash = (37 * hash) + REDEFINES_FIELD_NUMBER;
      hash = (53 * hash) + getRedefinesList().hashCode();
    }
    hash = (37 * hash) + IS_DEFAULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsDefault());
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getDirection().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.AddMemberEdit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.AddMemberEdit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddMemberEdit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.AddMemberEdit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AddMemberEdit inserts a declaration into a namespace or the document root.
   * </pre>
   *
   * Protobuf type {@code sysml.AddMemberEdit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.AddMemberEdit)
      org.openmbee.opensysml.proto.AddMemberEditOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddMemberEdit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddMemberEdit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.AddMemberEdit.class, org.openmbee.opensysml.proto.AddMemberEdit.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.AddMemberEdit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      owner_ = "";
      kind_ = "";
      name_ = "";
      type_ = "";
      multiplicity_ = "";
      value_ = "";
      specializes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      isAbstract_ = false;
      redefines_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      isDefault_ = false;
      direction_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddMemberEdit_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddMemberEdit getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.AddMemberEdit.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddMemberEdit build() {
      org.openmbee.opensysml.proto.AddMemberEdit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddMemberEdit buildPartial() {
      org.openmbee.opensysml.proto.AddMemberEdit result = new org.openmbee.opensysml.proto.AddMemberEdit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.AddMemberEdit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.owner_ = owner_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kind_ = kind_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.multiplicity_ = multiplicity_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        specializes_.makeImmutable();
        result.specializes_ = specializes_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.isAbstract_ = isAbstract_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        redefines_.makeImmutable();
        result.redefines_ = redefines_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.isDefault_ = isDefault_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.direction_ = direction_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.AddMemberEdit) {
        return mergeFrom((org.openmbee.opensysml.proto.AddMemberEdit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.AddMemberEdit other) {
      if (other == org.openmbee.opensysml.proto.AddMemberEdit.getDefaultInstance()) return this;
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getKind().isEmpty()) {
        kind_ = other.kind_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getMultiplicity().isEmpty()) {
        multiplicity_ = other.multiplicity_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.specializes_.isEmpty()) {
        if (specializes_.isEmpty()) {
          specializes_ = other.specializes_;
          bitField0_ |= 0x00000040;
        } else {
          ensureSpecializesIsMutable();
          specializes_.addAll(other.specializes_);
        }
        onChanged();
      }
      if (other.getIsAbstract() != false) {
        setIsAbstract(other.getIsAbstract());
      }
      if (!other.redefines_.isEmpty()) {
        if (redefines_.isEmpty()) {
          redefines_ = other.redefines_;
          bitField0_ |= 0x00000100;
        } else {
          ensureRedefinesIsMutable();
          redefines_.addAll(other.redefines_);
        }
        onChanged();
      }
      if (other.getIsDefault() != false) {
        setIsDefault(other.getIsDefault());
      }
      if (!other.getDirection().isEmpty()) {
        direction_ = other.direction_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              owner_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              kind_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              multiplicity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              value_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSpecializesIsMutable();
              specializes_.add(s);
              break;
            } // case 58
            case 64: {
              isAbstract_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureRedefinesIsMutable();
              redefines_.add(s);
              break;
            } // case 74
            case 80: {
              isDefault_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              direction_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object owner_ = "";
    /**
     * <pre>
     * Namespace FQN to receive the declaration; empty means the document root.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The owner.
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Namespace FQN to receive the declaration; empty means the document root.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The bytes for owner.
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Namespace FQN to receive the declaration; empty means the document root.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespace FQN to receive the declaration; empty means the document root.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOwner() {
      owner_ = getDefaultInstance().getOwner();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Namespace FQN to receive the declaration; empty means the document root.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The bytes for owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object kind_ = "";
    /**
     * <pre>
     * Written declaration kind, such as "part def" or "class".
     * </pre>
     *
     * <code>string kind = 2 [json_name = "kind"];</code>
     * @return The kind.
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Written declaration kind, such as "part def" or "class".
     * </pre>
     *
     * <code>string kind = 2 [json_name = "kind"];</code>
     * @return The bytes for kind.
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Written declaration kind, such as "part def" or "class".
     * </pre>
     *
     * <code>string kind = 2 [json_name = "kind"];</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kind_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Written declaration kind, such as "part def" or "class".
     * </pre>
     *
     * <code>string kind = 2 [json_name = "kind"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      kind_ = getDefaultInstance().getKind();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Written declaration kind, such as "part def" or "class".
     * </pre>
     *
     * <code>string kind = 2 [json_name = "kind"];</code>
     * @param value The bytes for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kind_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Declared identifier.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Declared identifier.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Declared identifier.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Declared identifier.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Declared identifier.
     * </pre>
     *
     * <code>string name = 3 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * Optional type target for a usage, written as notation.
     * </pre>
     *
     * <code>string type = 4 [json_name = "type"];</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional type target for a usage, written as notation.
     * </pre>
     *
     * <code>string type = 4 [json_name = "type"];</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional type target for a usage, written as notation.
     * </pre>
     *
     * <code>string type = 4 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional type target for a usage, written as notation.
     * </pre>
     *
     * <code>string type = 4 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional type target for a usage, written as notation.
     * </pre>
     *
     * <code>string type = 4 [json_name = "type"];</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object multiplicity_ = "";
    /**
     * <pre>
     * Optional multiplicity, including brackets, such as "[0..*]".
     * </pre>
     *
     * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
     * @return The multiplicity.
     */
    public java.lang.String getMultiplicity() {
      java.lang.Object ref = multiplicity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        multiplicity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional multiplicity, including brackets, such as "[0..*]".
     * </pre>
     *
     * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
     * @return The bytes for multiplicity.
     */
    public com.google.protobuf.ByteString
        getMultiplicityBytes() {
      java.lang.Object ref = multiplicity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        multiplicity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional multiplicity, including brackets, such as "[0..*]".
     * </pre>
     *
     * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
     * @param value The multiplicity to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplicity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      multiplicity_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional multiplicity, including brackets, such as "[0..*]".
     * </pre>
     *
     * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiplicity() {
      multiplicity_ = getDefaultInstance().getMultiplicity();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional multiplicity, including brackets, such as "[0..*]".
     * </pre>
     *
     * <code>string multiplicity = 5 [json_name = "multiplicity"];</code>
     * @param value The bytes for multiplicity to set.
     * @return This builder for chaining.
     */
    public Builder setMultiplicityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      multiplicity_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <pre>
     * Optional value expression, written as notation.
     * </pre>
     *
     * <code>string value = 6 [json_name = "value"];</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional value expression, written as notation.
     * </pre>
     *
     * <code>string value = 6 [json_name = "value"];</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional value expression, written as notation.
     * </pre>
     *
     * <code>string value = 6 [json_name = "value"];</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      value_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional value expression, written as notation.
     * </pre>
     *
     * <code>string value = 6 [json_name = "value"];</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      value_ = getDefaultInstance().getValue();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional value expression, written as notation.
     * </pre>
     *
     * <code>string value = 6 [json_name = "value"];</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      value_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList specializes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSpecializesIsMutable() {
      if (!specializes_.isModifiable()) {
        specializes_ = new com.google.protobuf.LazyStringArrayList(specializes_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @return A list containing the specializes.
     */
    public com.google.protobuf.ProtocolStringList
        getSpecializesList() {
      specializes_.makeImmutable();
      return specializes_;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @return The count of specializes.
     */
    public int getSpecializesCount() {
      return specializes_.size();
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param index The index of the element to return.
     * @return The specializes at the given index.
     */
    public java.lang.String getSpecializes(int index) {
      return specializes_.get(index);
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the specializes at the given index.
     */
    public com.google.protobuf.ByteString
        getSpecializesBytes(int index) {
      return specializes_.getByteString(index);
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param index The index to set the value at.
     * @param value The specializes to set.
     * @return This builder for chaining.
     */
    public Builder setSpecializes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSpecializesIsMutable();
      specializes_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param value The specializes to add.
     * @return This builder for chaining.
     */
    public Builder addSpecializes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSpecializesIsMutable();
      specializes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param values The specializes to add.
     * @return This builder for chaining.
     */
    public Builder addAllSpecializes(
        java.lang.Iterable<java.lang.String> values) {
      ensureSpecializesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, specializes_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecializes() {
      specializes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional specialization targets for a definition.
     * </pre>
     *
     * <code>repeated string specializes = 7 [json_name = "specializes"];</code>
     * @param value The bytes of the specializes to add.
     * @return This builder for chaining.
     */
    public Builder addSpecializesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSpecializesIsMutable();
      specializes_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private boolean isAbstract_ ;
    /**
     * <pre>
     * Whether the declaration is abstract.
     * </pre>
     *
     * <code>bool is_abstract = 8 [json_name = "isAbstract"];</code>
     * @return The isAbstract.
     */
    @java.lang.Override
    public boolean getIsAbstract() {
      return isAbstract_;
    }
    /**
     * <pre>
     * Whether the declaration is abstract.
     * </pre>
     *
     * <code>bool is_abstract = 8 [json_name = "isAbstract"];</code>
     * @param value The isAbstract to set.
     * @return This builder for chaining.
     */
    public Builder setIsAbstract(boolean value) {

      isAbstract_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the declaration is abstract.
     * </pre>
     *
     * <code>bool is_abstract = 8 [json_name = "isAbstract"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAbstract() {
      bitField0_ = (bitField0_ & ~0x00000080);
      isAbstract_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList redefines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureRedefinesIsMutable() {
      if (!redefines_.isModifiable()) {
        redefines_ = new com.google.protobuf.LazyStringArrayList(redefines_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @return A list containing the redefines.
     */
    public com.google.protobuf.ProtocolStringList
        getRedefinesList() {
      redefines_.makeImmutable();
      return redefines_;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @return The count of redefines.
     */
    public int getRedefinesCount() {
      return redefines_.size();
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param index The index of the element to return.
     * @return The redefines at the given index.
     */
    public java.lang.String getRedefines(int index) {
      return redefines_.get(index);
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the redefines at the given index.
     */
    public com.google.protobuf.ByteString
        getRedefinesBytes(int index) {
      return redefines_.getByteString(index);
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param index The index to set the value at.
     * @param value The redefines to set.
     * @return This builder for chaining.
     */
    public Builder setRedefines(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRedefinesIsMutable();
      redefines_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param value The redefines to add.
     * @return This builder for chaining.
     */
    public Builder addRedefines(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureRedefinesIsMutable();
      redefines_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param values The redefines to add.
     * @return This builder for chaining.
     */
    public Builder addAllRedefines(
        java.lang.Iterable<java.lang.String> values) {
      ensureRedefinesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, redefines_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRedefines() {
      redefines_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional redefinition targets for a usage.
     * </pre>
     *
     * <code>repeated string redefines = 9 [json_name = "redefines"];</code>
     * @param value The bytes of the redefines to add.
     * @return This builder for chaining.
     */
    public Builder addRedefinesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureRedefinesIsMutable();
      redefines_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private boolean isDefault_ ;
    /**
     * <pre>
     * Whether the value uses the default assignment keyword.
     * </pre>
     *
     * <code>bool is_default = 10 [json_name = "isDefault"];</code>
     * @return The isDefault.
     */
    @java.lang.Override
    public boolean getIsDefault() {
      return isDefault_;
    }
    /**
     * <pre>
     * Whether the value uses the default assignment keyword.
     * </pre>
     *
     * <code>bool is_default = 10 [json_name = "isDefault"];</code>
     * @param value The isDefault to set.
     * @return This builder for chaining.
     */
    public Builder setIsDefault(boolean value) {

      isDefault_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the value uses the default assignment keyword.
     * </pre>
     *
     * <code>bool is_default = 10 [json_name = "isDefault"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDefault() {
      bitField0_ = (bitField0_ & ~0x00000200);
      isDefault_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object direction_ = "";
    /**
     * <pre>
     * Optional usage direction: "in", "out" or "inout".
     * </pre>
     *
     * <code>string direction = 11 [json_name = "direction"];</code>
     * @return The direction.
     */
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional usage direction: "in", "out" or "inout".
     * </pre>
     *
     * <code>string direction = 11 [json_name = "direction"];</code>
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional usage direction: "in", "out" or "inout".
     * </pre>
     *
     * <code>string direction = 11 [json_name = "direction"];</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      direction_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional usage direction: "in", "out" or "inout".
     * </pre>
     *
     * <code>string direction = 11 [json_name = "direction"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      direction_ = getDefaultInstance().getDirection();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional usage direction: "in", "out" or "inout".
     * </pre>
     *
     * <code>string direction = 11 [json_name = "direction"];</code>
     * @param value The bytes for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      direction_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.AddMemberEdit)
  }

  // @@protoc_insertion_point(class_scope:sysml.AddMemberEdit)
  private static final org.openmbee.opensysml.proto.AddMemberEdit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.AddMemberEdit();
  }

  public static org.openmbee.opensysml.proto.AddMemberEdit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddMemberEdit>
      PARSER = new com.google.protobuf.AbstractParser<AddMemberEdit>() {
    @java.lang.Override
    public AddMemberEdit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddMemberEdit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddMemberEdit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.AddMemberEdit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

