// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface AddRequirementConstraintEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.AddRequirementConstraintEdit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Requirement-like namespace receiving the constraint.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * Requirement-like namespace receiving the constraint.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Constraint kind: "require" or "assume".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <pre>
   * Constraint kind: "require" or "assume".
   * </pre>
   *
   * <code>string kind = 2 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <pre>
   * Constraint expression, written as notation.
   * </pre>
   *
   * <code>string expression = 3 [json_name = "expression"];</code>
   * @return The expression.
   */
  java.lang.String getExpression();
  /**
   * <pre>
   * Constraint expression, written as notation.
   * </pre>
   *
   * <code>string expression = 3 [json_name = "expression"];</code>
   * @return The bytes for expression.
   */
  com.google.protobuf.ByteString
      getExpressionBytes();

  /**
   * <pre>
   * Optional declared name.
   * </pre>
   *
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Optional declared name.
   * </pre>
   *
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
