// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface AddSatisfyEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.AddSatisfyEdit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Body receiving the usage.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * Body receiving the usage.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Requirement feature reference.
   * </pre>
   *
   * <code>string requirement = 2 [json_name = "requirement"];</code>
   * @return The requirement.
   */
  java.lang.String getRequirement();
  /**
   * <pre>
   * Requirement feature reference.
   * </pre>
   *
   * <code>string requirement = 2 [json_name = "requirement"];</code>
   * @return The bytes for requirement.
   */
  com.google.protobuf.ByteString
      getRequirementBytes();

  /**
   * <pre>
   * Optional satisfying feature reference.
   * </pre>
   *
   * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
   * @return The satisfyingFeature.
   */
  java.lang.String getSatisfyingFeature();
  /**
   * <pre>
   * Optional satisfying feature reference.
   * </pre>
   *
   * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
   * @return The bytes for satisfyingFeature.
   */
  com.google.protobuf.ByteString
      getSatisfyingFeatureBytes();

  /**
   * <pre>
   * Whether the usage is asserted.
   * </pre>
   *
   * <code>bool is_asserted = 4 [json_name = "isAsserted"];</code>
   * @return The isAsserted.
   */
  boolean getIsAsserted();

  /**
   * <pre>
   * Whether the usage is negated.
   * </pre>
   *
   * <code>bool is_negated = 5 [json_name = "isNegated"];</code>
   * @return The isNegated.
   */
  boolean getIsNegated();
}
