// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * AddSatisfyEdit inserts a satisfy usage into any package or body that admits behavior usages.
 * </pre>
 *
 * Protobuf type {@code sysml.AddSatisfyEdit}
 */
@com.google.protobuf.Generated
public final class AddSatisfyEdit extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.AddSatisfyEdit)
    AddSatisfyEditOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AddSatisfyEdit");
  }
  // Use AddSatisfyEdit.newBuilder() to construct.
  private AddSatisfyEdit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddSatisfyEdit() {
    owner_ = "";
    requirement_ = "";
    satisfyingFeature_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSatisfyEdit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSatisfyEdit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.AddSatisfyEdit.class, org.openmbee.opensysml.proto.AddSatisfyEdit.Builder.class);
  }

  public static final int OWNER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object owner_ = "";
  /**
   * <pre>
   * Body receiving the usage.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  @java.lang.Override
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Body receiving the usage.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUIREMENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requirement_ = "";
  /**
   * <pre>
   * Requirement feature reference.
   * </pre>
   *
   * <code>string requirement = 2 [json_name = "requirement"];</code>
   * @return The requirement.
   */
  @java.lang.Override
  public java.lang.String getRequirement() {
    java.lang.Object ref = requirement_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requirement_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Requirement feature reference.
   * </pre>
   *
   * <code>string requirement = 2 [json_name = "requirement"];</code>
   * @return The bytes for requirement.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequirementBytes() {
    java.lang.Object ref = requirement_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requirement_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SATISFYING_FEATURE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object satisfyingFeature_ = "";
  /**
   * <pre>
   * Optional satisfying feature reference.
   * </pre>
   *
   * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
   * @return The satisfyingFeature.
   */
  @java.lang.Override
  public java.lang.String getSatisfyingFeature() {
    java.lang.Object ref = satisfyingFeature_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      satisfyingFeature_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional satisfying feature reference.
   * </pre>
   *
   * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
   * @return The bytes for satisfyingFeature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSatisfyingFeatureBytes() {
    java.lang.Object ref = satisfyingFeature_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      satisfyingFeature_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_ASSERTED_FIELD_NUMBER = 4;
  private boolean isAsserted_ = false;
  /**
   * <pre>
   * Whether the usage is asserted.
   * </pre>
   *
   * <code>bool is_asserted = 4 [json_name = "isAsserted"];</code>
   * @return The isAsserted.
   */
  @java.lang.Override
  public boolean getIsAsserted() {
    return isAsserted_;
  }

  public static final int IS_NEGATED_FIELD_NUMBER = 5;
  private boolean isNegated_ = false;
  /**
   * <pre>
   * Whether the usage is negated.
   * </pre>
   *
   * <code>bool is_negated = 5 [json_name = "isNegated"];</code>
   * @return The isNegated.
   */
  @java.lang.Override
  public boolean getIsNegated() {
    return isNegated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requirement_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, requirement_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(satisfyingFeature_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, satisfyingFeature_);
    }
    if (isAsserted_ != false) {
      output.writeBool(4, isAsserted_);
    }
    if (isNegated_ != false) {
      output.writeBool(5, isNegated_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requirement_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requirement_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(satisfyingFeature_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, satisfyingFeature_);
    }
    if (isAsserted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isAsserted_);
    }
    if (isNegated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isNegated_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.AddSatisfyEdit)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.AddSatisfyEdit other = (org.openmbee.opensysml.proto.AddSatisfyEdit) obj;

    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (!getRequirement()
        .equals(other.getRequirement())) return false;
    if (!getSatisfyingFeature()
        .equals(other.getSatisfyingFeature())) return false;
    if (getIsAsserted()
        != other.getIsAsserted()) return false;
    if (getIsNegated()
        != other.getIsNegated()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + REQUIREMENT_FIELD_NUMBER;
    hash = (53 * hash) + getRequirement().hashCode();
    hash = (37 * hash) + SATISFYING_FEATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSatisfyingFeature().hashCode();
    hash = (37 * hash) + IS_ASSERTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAsserted());
    hash = (37 * hash) + IS_NEGATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNegated());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddSatisfyEdit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.AddSatisfyEdit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AddSatisfyEdit inserts a satisfy usage into any package or body that admits behavior usages.
   * </pre>
   *
   * Protobuf type {@code sysml.AddSatisfyEdit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.AddSatisfyEdit)
      org.openmbee.opensysml.proto.AddSatisfyEditOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSatisfyEdit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSatisfyEdit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.AddSatisfyEdit.class, org.openmbee.opensysml.proto.AddSatisfyEdit.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.AddSatisfyEdit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      owner_ = "";
      requirement_ = "";
      satisfyingFeature_ = "";
      isAsserted_ = false;
      isNegated_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddSatisfyEdit_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSatisfyEdit getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.AddSatisfyEdit.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSatisfyEdit build() {
      org.openmbee.opensysml.proto.AddSatisfyEdit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddSatisfyEdit buildPartial() {
      org.openmbee.opensysml.proto.AddSatisfyEdit result = new org.openmbee.opensysml.proto.AddSatisfyEdit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.AddSatisfyEdit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.owner_ = owner_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requirement_ = requirement_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.satisfyingFeature_ = satisfyingFeature_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isAsserted_ = isAsserted_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isNegated_ = isNegated_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.AddSatisfyEdit) {
        return mergeFrom((org.openmbee.opensysml.proto.AddSatisfyEdit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.AddSatisfyEdit other) {
      if (other == org.openmbee.opensysml.proto.AddSatisfyEdit.getDefaultInstance()) return this;
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRequirement().isEmpty()) {
        requirement_ = other.requirement_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSatisfyingFeature().isEmpty()) {
        satisfyingFeature_ = other.satisfyingFeature_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getIsAsserted() != false) {
        setIsAsserted(other.getIsAsserted());
      }
      if (other.getIsNegated() != false) {
        setIsNegated(other.getIsNegated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              owner_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              requirement_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              satisfyingFeature_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              isAsserted_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              isNegated_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object owner_ = "";
    /**
     * <pre>
     * Body receiving the usage.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The owner.
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Body receiving the usage.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The bytes for owner.
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Body receiving the usage.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body receiving the usage.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOwner() {
      owner_ = getDefaultInstance().getOwner();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body receiving the usage.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The bytes for owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object requirement_ = "";
    /**
     * <pre>
     * Requirement feature reference.
     * </pre>
     *
     * <code>string requirement = 2 [json_name = "requirement"];</code>
     * @return The requirement.
     */
    public java.lang.String getRequirement() {
      java.lang.Object ref = requirement_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requirement_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Requirement feature reference.
     * </pre>
     *
     * <code>string requirement = 2 [json_name = "requirement"];</code>
     * @return The bytes for requirement.
     */
    public com.google.protobuf.ByteString
        getRequirementBytes() {
      java.lang.Object ref = requirement_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requirement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Requirement feature reference.
     * </pre>
     *
     * <code>string requirement = 2 [json_name = "requirement"];</code>
     * @param value The requirement to set.
     * @return This builder for chaining.
     */
    public Builder setRequirement(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requirement_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Requirement feature reference.
     * </pre>
     *
     * <code>string requirement = 2 [json_name = "requirement"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequirement() {
      requirement_ = getDefaultInstance().getRequirement();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Requirement feature reference.
     * </pre>
     *
     * <code>string requirement = 2 [json_name = "requirement"];</code>
     * @param value The bytes for requirement to set.
     * @return This builder for chaining.
     */
    public Builder setRequirementBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requirement_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object satisfyingFeature_ = "";
    /**
     * <pre>
     * Optional satisfying feature reference.
     * </pre>
     *
     * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
     * @return The satisfyingFeature.
     */
    public java.lang.String getSatisfyingFeature() {
      java.lang.Object ref = satisfyingFeature_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        satisfyingFeature_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional satisfying feature reference.
     * </pre>
     *
     * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
     * @return The bytes for satisfyingFeature.
     */
    public com.google.protobuf.ByteString
        getSatisfyingFeatureBytes() {
      java.lang.Object ref = satisfyingFeature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        satisfyingFeature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional satisfying feature reference.
     * </pre>
     *
     * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
     * @param value The satisfyingFeature to set.
     * @return This builder for chaining.
     */
    public Builder setSatisfyingFeature(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      satisfyingFeature_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional satisfying feature reference.
     * </pre>
     *
     * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSatisfyingFeature() {
      satisfyingFeature_ = getDefaultInstance().getSatisfyingFeature();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional satisfying feature reference.
     * </pre>
     *
     * <code>string satisfying_feature = 3 [json_name = "satisfyingFeature"];</code>
     * @param value The bytes for satisfyingFeature to set.
     * @return This builder for chaining.
     */
    public Builder setSatisfyingFeatureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      satisfyingFeature_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean isAsserted_ ;
    /**
     * <pre>
     * Whether the usage is asserted.
     * </pre>
     *
     * <code>bool is_asserted = 4 [json_name = "isAsserted"];</code>
     * @return The isAsserted.
     */
    @java.lang.Override
    public boolean getIsAsserted() {
      return isAsserted_;
    }
    /**
     * <pre>
     * Whether the usage is asserted.
     * </pre>
     *
     * <code>bool is_asserted = 4 [json_name = "isAsserted"];</code>
     * @param value The isAsserted to set.
     * @return This builder for chaining.
     */
    public Builder setIsAsserted(boolean value) {

      isAsserted_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the usage is asserted.
     * </pre>
     *
     * <code>bool is_asserted = 4 [json_name = "isAsserted"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAsserted() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isAsserted_ = false;
      onChanged();
      return this;
    }

    private boolean isNegated_ ;
    /**
     * <pre>
     * Whether the usage is negated.
     * </pre>
     *
     * <code>bool is_negated = 5 [json_name = "isNegated"];</code>
     * @return The isNegated.
     */
    @java.lang.Override
    public boolean getIsNegated() {
      return isNegated_;
    }
    /**
     * <pre>
     * Whether the usage is negated.
     * </pre>
     *
     * <code>bool is_negated = 5 [json_name = "isNegated"];</code>
     * @param value The isNegated to set.
     * @return This builder for chaining.
     */
    public Builder setIsNegated(boolean value) {

      isNegated_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the usage is negated.
     * </pre>
     *
     * <code>bool is_negated = 5 [json_name = "isNegated"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNegated() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isNegated_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.AddSatisfyEdit)
  }

  // @@protoc_insertion_point(class_scope:sysml.AddSatisfyEdit)
  private static final org.openmbee.opensysml.proto.AddSatisfyEdit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.AddSatisfyEdit();
  }

  public static org.openmbee.opensysml.proto.AddSatisfyEdit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddSatisfyEdit>
      PARSER = new com.google.protobuf.AbstractParser<AddSatisfyEdit>() {
    @java.lang.Override
    public AddSatisfyEdit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddSatisfyEdit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddSatisfyEdit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.AddSatisfyEdit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

