// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * AddTransitionEdit inserts a transition usage, or an entry transition, into a state body.
 * </pre>
 *
 * Protobuf type {@code sysml.AddTransitionEdit}
 */
@com.google.protobuf.Generated
public final class AddTransitionEdit extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.AddTransitionEdit)
    AddTransitionEditOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "AddTransitionEdit");
  }
  // Use AddTransitionEdit.newBuilder() to construct.
  private AddTransitionEdit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddTransitionEdit() {
    owner_ = "";
    name_ = "";
    source_ = "";
    target_ = "";
    trigger_ = "";
    guard_ = "";
    effect_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddTransitionEdit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddTransitionEdit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.AddTransitionEdit.class, org.openmbee.opensysml.proto.AddTransitionEdit.Builder.class);
  }

  public static final int OWNER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object owner_ = "";
  /**
   * <pre>
   * State body receiving the transition.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  @java.lang.Override
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * State body receiving the transition.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Optional transition name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional transition name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * Source feature reference; empty only for an entry transition.
   * </pre>
   *
   * <code>string source = 3 [json_name = "source"];</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Source feature reference; empty only for an entry transition.
   * </pre>
   *
   * <code>string source = 3 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object target_ = "";
  /**
   * <pre>
   * Target feature reference.
   * </pre>
   *
   * <code>string target = 4 [json_name = "target"];</code>
   * @return The target.
   */
  @java.lang.Override
  public java.lang.String getTarget() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      target_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Target feature reference.
   * </pre>
   *
   * <code>string target = 4 [json_name = "target"];</code>
   * @return The bytes for target.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetBytes() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      target_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRIGGER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object trigger_ = "";
  /**
   * <pre>
   * Optional text after `accept`.
   * </pre>
   *
   * <code>string trigger = 5 [json_name = "trigger"];</code>
   * @return The trigger.
   */
  @java.lang.Override
  public java.lang.String getTrigger() {
    java.lang.Object ref = trigger_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      trigger_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional text after `accept`.
   * </pre>
   *
   * <code>string trigger = 5 [json_name = "trigger"];</code>
   * @return The bytes for trigger.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTriggerBytes() {
    java.lang.Object ref = trigger_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      trigger_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUARD_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object guard_ = "";
  /**
   * <pre>
   * Optional boolean expression after `if`.
   * </pre>
   *
   * <code>string guard = 6 [json_name = "guard"];</code>
   * @return The guard.
   */
  @java.lang.Override
  public java.lang.String getGuard() {
    java.lang.Object ref = guard_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guard_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional boolean expression after `if`.
   * </pre>
   *
   * <code>string guard = 6 [json_name = "guard"];</code>
   * @return The bytes for guard.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGuardBytes() {
    java.lang.Object ref = guard_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guard_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EFFECT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object effect_ = "";
  /**
   * <pre>
   * Optional effect text after `do`.
   * </pre>
   *
   * <code>string effect = 7 [json_name = "effect"];</code>
   * @return The effect.
   */
  @java.lang.Override
  public java.lang.String getEffect() {
    java.lang.Object ref = effect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      effect_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional effect text after `do`.
   * </pre>
   *
   * <code>string effect = 7 [json_name = "effect"];</code>
   * @return The bytes for effect.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEffectBytes() {
    java.lang.Object ref = effect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      effect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIAL_FIELD_NUMBER = 8;
  private boolean initial_ = false;
  /**
   * <pre>
   * Write `entry; then &lt;target&gt;;` instead of a regular transition.
   * </pre>
   *
   * <code>bool initial = 8 [json_name = "initial"];</code>
   * @return The initial.
   */
  @java.lang.Override
  public boolean getInitial() {
    return initial_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(target_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, target_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trigger_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, trigger_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(guard_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, guard_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(effect_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, effect_);
    }
    if (initial_ != false) {
      output.writeBool(8, initial_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(owner_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, owner_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(target_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, target_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(trigger_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, trigger_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(guard_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, guard_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(effect_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, effect_);
    }
    if (initial_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, initial_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.AddTransitionEdit)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.AddTransitionEdit other = (org.openmbee.opensysml.proto.AddTransitionEdit) obj;

    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getTarget()
        .equals(other.getTarget())) return false;
    if (!getTrigger()
        .equals(other.getTrigger())) return false;
    if (!getGuard()
        .equals(other.getGuard())) return false;
    if (!getEffect()
        .equals(other.getEffect())) return false;
    if (getInitial()
        != other.getInitial()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + TARGET_FIELD_NUMBER;
    hash = (53 * hash) + getTarget().hashCode();
    hash = (37 * hash) + TRIGGER_FIELD_NUMBER;
    hash = (53 * hash) + getTrigger().hashCode();
    hash = (37 * hash) + GUARD_FIELD_NUMBER;
    hash = (53 * hash) + getGuard().hashCode();
    hash = (37 * hash) + EFFECT_FIELD_NUMBER;
    hash = (53 * hash) + getEffect().hashCode();
    hash = (37 * hash) + INITIAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInitial());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.AddTransitionEdit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.AddTransitionEdit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.AddTransitionEdit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.AddTransitionEdit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AddTransitionEdit inserts a transition usage, or an entry transition, into a state body.
   * </pre>
   *
   * Protobuf type {@code sysml.AddTransitionEdit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.AddTransitionEdit)
      org.openmbee.opensysml.proto.AddTransitionEditOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddTransitionEdit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddTransitionEdit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.AddTransitionEdit.class, org.openmbee.opensysml.proto.AddTransitionEdit.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.AddTransitionEdit.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      owner_ = "";
      name_ = "";
      source_ = "";
      target_ = "";
      trigger_ = "";
      guard_ = "";
      effect_ = "";
      initial_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_AddTransitionEdit_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddTransitionEdit getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.AddTransitionEdit.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddTransitionEdit build() {
      org.openmbee.opensysml.proto.AddTransitionEdit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.AddTransitionEdit buildPartial() {
      org.openmbee.opensysml.proto.AddTransitionEdit result = new org.openmbee.opensysml.proto.AddTransitionEdit(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.AddTransitionEdit result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.owner_ = owner_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.target_ = target_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.trigger_ = trigger_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.guard_ = guard_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.effect_ = effect_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.initial_ = initial_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.AddTransitionEdit) {
        return mergeFrom((org.openmbee.opensysml.proto.AddTransitionEdit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.AddTransitionEdit other) {
      if (other == org.openmbee.opensysml.proto.AddTransitionEdit.getDefaultInstance()) return this;
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTarget().isEmpty()) {
        target_ = other.target_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTrigger().isEmpty()) {
        trigger_ = other.trigger_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getGuard().isEmpty()) {
        guard_ = other.guard_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getEffect().isEmpty()) {
        effect_ = other.effect_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getInitial() != false) {
        setInitial(other.getInitial());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              owner_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              target_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              trigger_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              guard_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              effect_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              initial_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object owner_ = "";
    /**
     * <pre>
     * State body receiving the transition.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The owner.
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * State body receiving the transition.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return The bytes for owner.
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * State body receiving the transition.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * State body receiving the transition.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOwner() {
      owner_ = getDefaultInstance().getOwner();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * State body receiving the transition.
     * </pre>
     *
     * <code>string owner = 1 [json_name = "owner"];</code>
     * @param value The bytes for owner to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      owner_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Optional transition name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional transition name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional transition name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional transition name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional transition name.
     * </pre>
     *
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * Source feature reference; empty only for an entry transition.
     * </pre>
     *
     * <code>string source = 3 [json_name = "source"];</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Source feature reference; empty only for an entry transition.
     * </pre>
     *
     * <code>string source = 3 [json_name = "source"];</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Source feature reference; empty only for an entry transition.
     * </pre>
     *
     * <code>string source = 3 [json_name = "source"];</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Source feature reference; empty only for an entry transition.
     * </pre>
     *
     * <code>string source = 3 [json_name = "source"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Source feature reference; empty only for an entry transition.
     * </pre>
     *
     * <code>string source = 3 [json_name = "source"];</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object target_ = "";
    /**
     * <pre>
     * Target feature reference.
     * </pre>
     *
     * <code>string target = 4 [json_name = "target"];</code>
     * @return The target.
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Target feature reference.
     * </pre>
     *
     * <code>string target = 4 [json_name = "target"];</code>
     * @return The bytes for target.
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Target feature reference.
     * </pre>
     *
     * <code>string target = 4 [json_name = "target"];</code>
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      target_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target feature reference.
     * </pre>
     *
     * <code>string target = 4 [json_name = "target"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      target_ = getDefaultInstance().getTarget();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target feature reference.
     * </pre>
     *
     * <code>string target = 4 [json_name = "target"];</code>
     * @param value The bytes for target to set.
     * @return This builder for chaining.
     */
    public Builder setTargetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      target_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object trigger_ = "";
    /**
     * <pre>
     * Optional text after `accept`.
     * </pre>
     *
     * <code>string trigger = 5 [json_name = "trigger"];</code>
     * @return The trigger.
     */
    public java.lang.String getTrigger() {
      java.lang.Object ref = trigger_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        trigger_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional text after `accept`.
     * </pre>
     *
     * <code>string trigger = 5 [json_name = "trigger"];</code>
     * @return The bytes for trigger.
     */
    public com.google.protobuf.ByteString
        getTriggerBytes() {
      java.lang.Object ref = trigger_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trigger_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional text after `accept`.
     * </pre>
     *
     * <code>string trigger = 5 [json_name = "trigger"];</code>
     * @param value The trigger to set.
     * @return This builder for chaining.
     */
    public Builder setTrigger(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      trigger_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional text after `accept`.
     * </pre>
     *
     * <code>string trigger = 5 [json_name = "trigger"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTrigger() {
      trigger_ = getDefaultInstance().getTrigger();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional text after `accept`.
     * </pre>
     *
     * <code>string trigger = 5 [json_name = "trigger"];</code>
     * @param value The bytes for trigger to set.
     * @return This builder for chaining.
     */
    public Builder setTriggerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      trigger_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object guard_ = "";
    /**
     * <pre>
     * Optional boolean expression after `if`.
     * </pre>
     *
     * <code>string guard = 6 [json_name = "guard"];</code>
     * @return The guard.
     */
    public java.lang.String getGuard() {
      java.lang.Object ref = guard_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guard_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional boolean expression after `if`.
     * </pre>
     *
     * <code>string guard = 6 [json_name = "guard"];</code>
     * @return The bytes for guard.
     */
    public com.google.protobuf.ByteString
        getGuardBytes() {
      java.lang.Object ref = guard_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional boolean expression after `if`.
     * </pre>
     *
     * <code>string guard = 6 [json_name = "guard"];</code>
     * @param value The guard to set.
     * @return This builder for chaining.
     */
    public Builder setGuard(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      guard_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional boolean expression after `if`.
     * </pre>
     *
     * <code>string guard = 6 [json_name = "guard"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGuard() {
      guard_ = getDefaultInstance().getGuard();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional boolean expression after `if`.
     * </pre>
     *
     * <code>string guard = 6 [json_name = "guard"];</code>
     * @param value The bytes for guard to set.
     * @return This builder for chaining.
     */
    public Builder setGuardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      guard_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object effect_ = "";
    /**
     * <pre>
     * Optional effect text after `do`.
     * </pre>
     *
     * <code>string effect = 7 [json_name = "effect"];</code>
     * @return The effect.
     */
    public java.lang.String getEffect() {
      java.lang.Object ref = effect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        effect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional effect text after `do`.
     * </pre>
     *
     * <code>string effect = 7 [json_name = "effect"];</code>
     * @return The bytes for effect.
     */
    public com.google.protobuf.ByteString
        getEffectBytes() {
      java.lang.Object ref = effect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        effect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional effect text after `do`.
     * </pre>
     *
     * <code>string effect = 7 [json_name = "effect"];</code>
     * @param value The effect to set.
     * @return This builder for chaining.
     */
    public Builder setEffect(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      effect_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional effect text after `do`.
     * </pre>
     *
     * <code>string effect = 7 [json_name = "effect"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEffect() {
      effect_ = getDefaultInstance().getEffect();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional effect text after `do`.
     * </pre>
     *
     * <code>string effect = 7 [json_name = "effect"];</code>
     * @param value The bytes for effect to set.
     * @return This builder for chaining.
     */
    public Builder setEffectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      effect_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private boolean initial_ ;
    /**
     * <pre>
     * Write `entry; then &lt;target&gt;;` instead of a regular transition.
     * </pre>
     *
     * <code>bool initial = 8 [json_name = "initial"];</code>
     * @return The initial.
     */
    @java.lang.Override
    public boolean getInitial() {
      return initial_;
    }
    /**
     * <pre>
     * Write `entry; then &lt;target&gt;;` instead of a regular transition.
     * </pre>
     *
     * <code>bool initial = 8 [json_name = "initial"];</code>
     * @param value The initial to set.
     * @return This builder for chaining.
     */
    public Builder setInitial(boolean value) {

      initial_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Write `entry; then &lt;target&gt;;` instead of a regular transition.
     * </pre>
     *
     * <code>bool initial = 8 [json_name = "initial"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInitial() {
      bitField0_ = (bitField0_ & ~0x00000080);
      initial_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.AddTransitionEdit)
  }

  // @@protoc_insertion_point(class_scope:sysml.AddTransitionEdit)
  private static final org.openmbee.opensysml.proto.AddTransitionEdit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.AddTransitionEdit();
  }

  public static org.openmbee.opensysml.proto.AddTransitionEdit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddTransitionEdit>
      PARSER = new com.google.protobuf.AbstractParser<AddTransitionEdit>() {
    @java.lang.Override
    public AddTransitionEdit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddTransitionEdit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddTransitionEdit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.AddTransitionEdit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

