// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface AddTransitionEditOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.AddTransitionEdit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * State body receiving the transition.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The owner.
   */
  java.lang.String getOwner();
  /**
   * <pre>
   * State body receiving the transition.
   * </pre>
   *
   * <code>string owner = 1 [json_name = "owner"];</code>
   * @return The bytes for owner.
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <pre>
   * Optional transition name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Optional transition name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Source feature reference; empty only for an entry transition.
   * </pre>
   *
   * <code>string source = 3 [json_name = "source"];</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * Source feature reference; empty only for an entry transition.
   * </pre>
   *
   * <code>string source = 3 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <pre>
   * Target feature reference.
   * </pre>
   *
   * <code>string target = 4 [json_name = "target"];</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * Target feature reference.
   * </pre>
   *
   * <code>string target = 4 [json_name = "target"];</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <pre>
   * Optional text after `accept`.
   * </pre>
   *
   * <code>string trigger = 5 [json_name = "trigger"];</code>
   * @return The trigger.
   */
  java.lang.String getTrigger();
  /**
   * <pre>
   * Optional text after `accept`.
   * </pre>
   *
   * <code>string trigger = 5 [json_name = "trigger"];</code>
   * @return The bytes for trigger.
   */
  com.google.protobuf.ByteString
      getTriggerBytes();

  /**
   * <pre>
   * Optional boolean expression after `if`.
   * </pre>
   *
   * <code>string guard = 6 [json_name = "guard"];</code>
   * @return The guard.
   */
  java.lang.String getGuard();
  /**
   * <pre>
   * Optional boolean expression after `if`.
   * </pre>
   *
   * <code>string guard = 6 [json_name = "guard"];</code>
   * @return The bytes for guard.
   */
  com.google.protobuf.ByteString
      getGuardBytes();

  /**
   * <pre>
   * Optional effect text after `do`.
   * </pre>
   *
   * <code>string effect = 7 [json_name = "effect"];</code>
   * @return The effect.
   */
  java.lang.String getEffect();
  /**
   * <pre>
   * Optional effect text after `do`.
   * </pre>
   *
   * <code>string effect = 7 [json_name = "effect"];</code>
   * @return The bytes for effect.
   */
  com.google.protobuf.ByteString
      getEffectBytes();

  /**
   * <pre>
   * Write `entry; then &lt;target&gt;;` instead of a regular transition.
   * </pre>
   *
   * <code>bool initial = 8 [json_name = "initial"];</code>
   * @return The initial.
   */
  boolean getInitial();
}
