// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface EditOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.EditOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   * @return Whether the setValue field is set.
   */
  boolean hasSetValue();
  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   * @return The setValue.
   */
  org.openmbee.opensysml.proto.SetValueEdit getSetValue();
  /**
   * <code>.sysml.SetValueEdit set_value = 1 [json_name = "setValue"];</code>
   */
  org.openmbee.opensysml.proto.SetValueEditOrBuilder getSetValueOrBuilder();

  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   * @return Whether the rename field is set.
   */
  boolean hasRename();
  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   * @return The rename.
   */
  org.openmbee.opensysml.proto.RenameEdit getRename();
  /**
   * <code>.sysml.RenameEdit rename = 2 [json_name = "rename"];</code>
   */
  org.openmbee.opensysml.proto.RenameEditOrBuilder getRenameOrBuilder();

  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   * @return Whether the addMember field is set.
   */
  boolean hasAddMember();
  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   * @return The addMember.
   */
  org.openmbee.opensysml.proto.AddMemberEdit getAddMember();
  /**
   * <code>.sysml.AddMemberEdit add_member = 3 [json_name = "addMember"];</code>
   */
  org.openmbee.opensysml.proto.AddMemberEditOrBuilder getAddMemberOrBuilder();

  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   * @return Whether the delete field is set.
   */
  boolean hasDelete();
  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   * @return The delete.
   */
  org.openmbee.opensysml.proto.DeleteEdit getDelete();
  /**
   * <code>.sysml.DeleteEdit delete = 4 [json_name = "delete"];</code>
   */
  org.openmbee.opensysml.proto.DeleteEditOrBuilder getDeleteOrBuilder();

  /**
   * <code>.sysml.MoveEdit move = 5 [json_name = "move"];</code>
   * @return Whether the move field is set.
   */
  boolean hasMove();
  /**
   * <code>.sysml.MoveEdit move = 5 [json_name = "move"];</code>
   * @return The move.
   */
  org.openmbee.opensysml.proto.MoveEdit getMove();
  /**
   * <code>.sysml.MoveEdit move = 5 [json_name = "move"];</code>
   */
  org.openmbee.opensysml.proto.MoveEditOrBuilder getMoveOrBuilder();

  /**
   * <code>.sysml.AddConnectionEdit add_connection = 6 [json_name = "addConnection"];</code>
   * @return Whether the addConnection field is set.
   */
  boolean hasAddConnection();
  /**
   * <code>.sysml.AddConnectionEdit add_connection = 6 [json_name = "addConnection"];</code>
   * @return The addConnection.
   */
  org.openmbee.opensysml.proto.AddConnectionEdit getAddConnection();
  /**
   * <code>.sysml.AddConnectionEdit add_connection = 6 [json_name = "addConnection"];</code>
   */
  org.openmbee.opensysml.proto.AddConnectionEditOrBuilder getAddConnectionOrBuilder();

  /**
   * <code>.sysml.AddSatisfyEdit add_satisfy = 7 [json_name = "addSatisfy"];</code>
   * @return Whether the addSatisfy field is set.
   */
  boolean hasAddSatisfy();
  /**
   * <code>.sysml.AddSatisfyEdit add_satisfy = 7 [json_name = "addSatisfy"];</code>
   * @return The addSatisfy.
   */
  org.openmbee.opensysml.proto.AddSatisfyEdit getAddSatisfy();
  /**
   * <code>.sysml.AddSatisfyEdit add_satisfy = 7 [json_name = "addSatisfy"];</code>
   */
  org.openmbee.opensysml.proto.AddSatisfyEditOrBuilder getAddSatisfyOrBuilder();

  /**
   * <code>.sysml.AddRequirementConstraintEdit add_requirement_constraint = 8 [json_name = "addRequirementConstraint"];</code>
   * @return Whether the addRequirementConstraint field is set.
   */
  boolean hasAddRequirementConstraint();
  /**
   * <code>.sysml.AddRequirementConstraintEdit add_requirement_constraint = 8 [json_name = "addRequirementConstraint"];</code>
   * @return The addRequirementConstraint.
   */
  org.openmbee.opensysml.proto.AddRequirementConstraintEdit getAddRequirementConstraint();
  /**
   * <code>.sysml.AddRequirementConstraintEdit add_requirement_constraint = 8 [json_name = "addRequirementConstraint"];</code>
   */
  org.openmbee.opensysml.proto.AddRequirementConstraintEditOrBuilder getAddRequirementConstraintOrBuilder();

  /**
   * <code>.sysml.AddTransitionEdit add_transition = 9 [json_name = "addTransition"];</code>
   * @return Whether the addTransition field is set.
   */
  boolean hasAddTransition();
  /**
   * <code>.sysml.AddTransitionEdit add_transition = 9 [json_name = "addTransition"];</code>
   * @return The addTransition.
   */
  org.openmbee.opensysml.proto.AddTransitionEdit getAddTransition();
  /**
   * <code>.sysml.AddTransitionEdit add_transition = 9 [json_name = "addTransition"];</code>
   */
  org.openmbee.opensysml.proto.AddTransitionEditOrBuilder getAddTransitionOrBuilder();

  org.openmbee.opensysml.proto.EditOperation.OperationCase getOperationCase();
}
