// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * EngineInfo is one analysis engine: what it answers, how strongly it can, and
 * whether it can run here.
 * </pre>
 *
 * Protobuf type {@code sysml.EngineInfo}
 */
@com.google.protobuf.Generated
public final class EngineInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.EngineInfo)
    EngineInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "EngineInfo");
  }
  // Use EngineInfo.newBuilder() to construct.
  private EngineInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EngineInfo() {
    name_ = "";
    authority_ = "";
    answers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    bounds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    process_ = "";
    processFound_ = "";
    unavailable_ = "";
    kind_ = "";
    protocol_ = "";
    source_ = "";
    command_ = "";
    version_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_EngineInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_EngineInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.EngineInfo.class, org.openmbee.opensysml.proto.EngineInfo.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The engine's name, as a request's `engine` field selects it.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The engine's name, as a request's `engine` field selects it.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORITY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object authority_ = "";
  /**
   * <pre>
   * The strongest evidence the engine can ever produce, spelled as
   * Verdict.strength is.
   * </pre>
   *
   * <code>string authority = 2 [json_name = "authority"];</code>
   * @return The authority.
   */
  @java.lang.Override
  public java.lang.String getAuthority() {
    java.lang.Object ref = authority_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authority_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The strongest evidence the engine can ever produce, spelled as
   * Verdict.strength is.
   * </pre>
   *
   * <code>string authority = 2 [json_name = "authority"];</code>
   * @return The bytes for authority.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorityBytes() {
    java.lang.Object ref = authority_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authority_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANSWERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList answers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @return A list containing the answers.
   */
  public com.google.protobuf.ProtocolStringList
      getAnswersList() {
    return answers_;
  }
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @return The count of answers.
   */
  public int getAnswersCount() {
    return answers_.size();
  }
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @param index The index of the element to return.
   * @return The answers at the given index.
   */
  public java.lang.String getAnswers(int index) {
    return answers_.get(index);
  }
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the answers at the given index.
   */
  public com.google.protobuf.ByteString
      getAnswersBytes(int index) {
    return answers_.getByteString(index);
  }

  public static final int BOUNDS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList bounds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @return A list containing the bounds.
   */
  public com.google.protobuf.ProtocolStringList
      getBoundsList() {
    return bounds_;
  }
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @return The count of bounds.
   */
  public int getBoundsCount() {
    return bounds_.size();
  }
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @param index The index of the element to return.
   * @return The bounds at the given index.
   */
  public java.lang.String getBounds(int index) {
    return bounds_.get(index);
  }
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the bounds at the given index.
   */
  public com.google.protobuf.ByteString
      getBoundsBytes(int index) {
    return bounds_.getByteString(index);
  }

  public static final int PROCESS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object process_ = "";
  /**
   * <pre>
   * The external process the engine needs, empty for one running in-process;
   * `process_found` says where it was found when it was.
   * </pre>
   *
   * <code>string process = 5 [json_name = "process"];</code>
   * @return The process.
   */
  @java.lang.Override
  public java.lang.String getProcess() {
    java.lang.Object ref = process_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      process_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The external process the engine needs, empty for one running in-process;
   * `process_found` says where it was found when it was.
   * </pre>
   *
   * <code>string process = 5 [json_name = "process"];</code>
   * @return The bytes for process.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessBytes() {
    java.lang.Object ref = process_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      process_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESS_FOUND_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object processFound_ = "";
  /**
   * <code>string process_found = 6 [json_name = "processFound"];</code>
   * @return The processFound.
   */
  @java.lang.Override
  public java.lang.String getProcessFound() {
    java.lang.Object ref = processFound_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processFound_ = s;
      return s;
    }
  }
  /**
   * <code>string process_found = 6 [json_name = "processFound"];</code>
   * @return The bytes for processFound.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessFoundBytes() {
    java.lang.Object ref = processFound_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processFound_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READY_FIELD_NUMBER = 7;
  private boolean ready_ = false;
  /**
   * <pre>
   * True when the engine can run: it is served, and it needs no process or its
   * process was found.
   * </pre>
   *
   * <code>bool ready = 7 [json_name = "ready"];</code>
   * @return The ready.
   */
  @java.lang.Override
  public boolean getReady() {
    return ready_;
  }

  public static final int UNAVAILABLE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unavailable_ = "";
  /**
   * <pre>
   * Why the engine cannot run, empty when it can.
   * </pre>
   *
   * <code>string unavailable = 8 [json_name = "unavailable"];</code>
   * @return The unavailable.
   */
  @java.lang.Override
  public java.lang.String getUnavailable() {
    java.lang.Object ref = unavailable_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unavailable_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Why the engine cannot run, empty when it can.
   * </pre>
   *
   * <code>string unavailable = 8 [json_name = "unavailable"];</code>
   * @return The bytes for unavailable.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnavailableBytes() {
    java.lang.Object ref = unavailable_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unavailable_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KIND_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kind_ = "";
  /**
   * <pre>
   * Where the engine comes from: "built-in" for the build's own, else the kind
   * of the manifest entry that registered it: "tool", "engine", "policy" or
   * "sampler". The fields below are empty for a built-in engine.
   * </pre>
   *
   * <code>string kind = 9 [json_name = "kind"];</code>
   * @return The kind.
   */
  @java.lang.Override
  public java.lang.String getKind() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kind_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Where the engine comes from: "built-in" for the build's own, else the kind
   * of the manifest entry that registered it: "tool", "engine", "policy" or
   * "sampler". The fields below are empty for a built-in engine.
   * </pre>
   *
   * <code>string kind = 9 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKindBytes() {
    java.lang.Object ref = kind_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kind_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOL_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object protocol_ = "";
  /**
   * <pre>
   * How the engine is spoken to: "-" for one built in; for a tool, "object"
   * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
   * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
   * when the reply block reads another format (the format alone when the entry
   * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
   * </pre>
   *
   * <code>string protocol = 10 [json_name = "protocol"];</code>
   * @return The protocol.
   */
  @java.lang.Override
  public java.lang.String getProtocol() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * How the engine is spoken to: "-" for one built in; for a tool, "object"
   * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
   * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
   * when the reply block reads another format (the format alone when the entry
   * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
   * </pre>
   *
   * <code>string protocol = 10 [json_name = "protocol"];</code>
   * @return The bytes for protocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * The manifest entry the engine was registered from, the command it resolved
   * to and the version the entry declares.
   * </pre>
   *
   * <code>string source = 11 [json_name = "source"];</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The manifest entry the engine was registered from, the command it resolved
   * to and the version the entry declares.
   * </pre>
   *
   * <code>string source = 11 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object command_ = "";
  /**
   * <code>string command = 12 [json_name = "command"];</code>
   * @return The command.
   */
  @java.lang.Override
  public java.lang.String getCommand() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      command_ = s;
      return s;
    }
  }
  /**
   * <code>string command = 12 [json_name = "command"];</code>
   * @return The bytes for command.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandBytes() {
    java.lang.Object ref = command_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      command_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <code>string version = 13 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 13 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVED_FIELD_NUMBER = 14;
  private boolean served_ = false;
  /**
   * <pre>
   * True when this service runs the engine for a request that reaches it. A
   * manifest engine is listed but not served until the service is started with
   * -serve-external-engines naming it; a request naming one that is not served
   * is FAILED_PRECONDITION.
   * </pre>
   *
   * <code>bool served = 14 [json_name = "served"];</code>
   * @return The served.
   */
  @java.lang.Override
  public boolean getServed() {
    return served_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authority_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, authority_);
    }
    for (int i = 0; i < answers_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, answers_.getRaw(i));
    }
    for (int i = 0; i < bounds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, bounds_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(process_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, process_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processFound_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, processFound_);
    }
    if (ready_ != false) {
      output.writeBool(7, ready_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unavailable_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, unavailable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kind_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(protocol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(command_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 12, command_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 13, version_);
    }
    if (served_ != false) {
      output.writeBool(14, served_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authority_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, authority_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < answers_.size(); i++) {
        dataSize += computeStringSizeNoTag(answers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAnswersList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < bounds_.size(); i++) {
        dataSize += computeStringSizeNoTag(bounds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getBoundsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(process_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, process_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processFound_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, processFound_);
    }
    if (ready_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, ready_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unavailable_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, unavailable_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kind_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(protocol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(command_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(12, command_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(13, version_);
    }
    if (served_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, served_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.EngineInfo)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.EngineInfo other = (org.openmbee.opensysml.proto.EngineInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getAuthority()
        .equals(other.getAuthority())) return false;
    if (!getAnswersList()
        .equals(other.getAnswersList())) return false;
    if (!getBoundsList()
        .equals(other.getBoundsList())) return false;
    if (!getProcess()
        .equals(other.getProcess())) return false;
    if (!getProcessFound()
        .equals(other.getProcessFound())) return false;
    if (getReady()
        != other.getReady()) return false;
    if (!getUnavailable()
        .equals(other.getUnavailable())) return false;
    if (!getKind()
        .equals(other.getKind())) return false;
    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getCommand()
        .equals(other.getCommand())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (getServed()
        != other.getServed()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AUTHORITY_FIELD_NUMBER;
    hash = (53 * hash) + getAuthority().hashCode();
    if (getAnswersCount() > 0) {
      hash = (37 * hash) + ANSWERS_FIELD_NUMBER;
      hash = (53 * hash) + getAnswersList().hashCode();
    }
    if (getBoundsCount() > 0) {
      hash = (37 * hash) + BOUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getBoundsList().hashCode();
    }
    hash = (37 * hash) + PROCESS_FIELD_NUMBER;
    hash = (53 * hash) + getProcess().hashCode();
    hash = (37 * hash) + PROCESS_FOUND_FIELD_NUMBER;
    hash = (53 * hash) + getProcessFound().hashCode();
    hash = (37 * hash) + READY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReady());
    hash = (37 * hash) + UNAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getUnavailable().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + getKind().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + getCommand().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + SERVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getServed());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.EngineInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.EngineInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.EngineInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.EngineInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * EngineInfo is one analysis engine: what it answers, how strongly it can, and
   * whether it can run here.
   * </pre>
   *
   * Protobuf type {@code sysml.EngineInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.EngineInfo)
      org.openmbee.opensysml.proto.EngineInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_EngineInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_EngineInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.EngineInfo.class, org.openmbee.opensysml.proto.EngineInfo.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.EngineInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      authority_ = "";
      answers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      bounds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      process_ = "";
      processFound_ = "";
      ready_ = false;
      unavailable_ = "";
      kind_ = "";
      protocol_ = "";
      source_ = "";
      command_ = "";
      version_ = "";
      served_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_EngineInfo_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.EngineInfo getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.EngineInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.EngineInfo build() {
      org.openmbee.opensysml.proto.EngineInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.EngineInfo buildPartial() {
      org.openmbee.opensysml.proto.EngineInfo result = new org.openmbee.opensysml.proto.EngineInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.EngineInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.authority_ = authority_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        answers_.makeImmutable();
        result.answers_ = answers_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        bounds_.makeImmutable();
        result.bounds_ = bounds_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.process_ = process_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.processFound_ = processFound_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.ready_ = ready_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.unavailable_ = unavailable_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.kind_ = kind_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.protocol_ = protocol_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.source_ = source_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.command_ = command_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.served_ = served_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.EngineInfo) {
        return mergeFrom((org.openmbee.opensysml.proto.EngineInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.EngineInfo other) {
      if (other == org.openmbee.opensysml.proto.EngineInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAuthority().isEmpty()) {
        authority_ = other.authority_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.answers_.isEmpty()) {
        if (answers_.isEmpty()) {
          answers_ = other.answers_;
          bitField0_ |= 0x00000004;
        } else {
          ensureAnswersIsMutable();
          answers_.addAll(other.answers_);
        }
        onChanged();
      }
      if (!other.bounds_.isEmpty()) {
        if (bounds_.isEmpty()) {
          bounds_ = other.bounds_;
          bitField0_ |= 0x00000008;
        } else {
          ensureBoundsIsMutable();
          bounds_.addAll(other.bounds_);
        }
        onChanged();
      }
      if (!other.getProcess().isEmpty()) {
        process_ = other.process_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getProcessFound().isEmpty()) {
        processFound_ = other.processFound_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getReady() != false) {
        setReady(other.getReady());
      }
      if (!other.getUnavailable().isEmpty()) {
        unavailable_ = other.unavailable_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getKind().isEmpty()) {
        kind_ = other.kind_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getCommand().isEmpty()) {
        command_ = other.command_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getServed() != false) {
        setServed(other.getServed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              authority_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAnswersIsMutable();
              answers_.add(s);
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureBoundsIsMutable();
              bounds_.add(s);
              break;
            } // case 34
            case 42: {
              process_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              processFound_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              ready_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              unavailable_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              kind_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              protocol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              command_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              served_ = input.readBool();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The engine's name, as a request's `engine` field selects it.
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The engine's name, as a request's `engine` field selects it.
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The engine's name, as a request's `engine` field selects it.
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The engine's name, as a request's `engine` field selects it.
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The engine's name, as a request's `engine` field selects it.
     * </pre>
     *
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object authority_ = "";
    /**
     * <pre>
     * The strongest evidence the engine can ever produce, spelled as
     * Verdict.strength is.
     * </pre>
     *
     * <code>string authority = 2 [json_name = "authority"];</code>
     * @return The authority.
     */
    public java.lang.String getAuthority() {
      java.lang.Object ref = authority_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authority_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The strongest evidence the engine can ever produce, spelled as
     * Verdict.strength is.
     * </pre>
     *
     * <code>string authority = 2 [json_name = "authority"];</code>
     * @return The bytes for authority.
     */
    public com.google.protobuf.ByteString
        getAuthorityBytes() {
      java.lang.Object ref = authority_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authority_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The strongest evidence the engine can ever produce, spelled as
     * Verdict.strength is.
     * </pre>
     *
     * <code>string authority = 2 [json_name = "authority"];</code>
     * @param value The authority to set.
     * @return This builder for chaining.
     */
    public Builder setAuthority(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      authority_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The strongest evidence the engine can ever produce, spelled as
     * Verdict.strength is.
     * </pre>
     *
     * <code>string authority = 2 [json_name = "authority"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthority() {
      authority_ = getDefaultInstance().getAuthority();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The strongest evidence the engine can ever produce, spelled as
     * Verdict.strength is.
     * </pre>
     *
     * <code>string authority = 2 [json_name = "authority"];</code>
     * @param value The bytes for authority to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      authority_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList answers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAnswersIsMutable() {
      if (!answers_.isModifiable()) {
        answers_ = new com.google.protobuf.LazyStringArrayList(answers_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @return A list containing the answers.
     */
    public com.google.protobuf.ProtocolStringList
        getAnswersList() {
      answers_.makeImmutable();
      return answers_;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @return The count of answers.
     */
    public int getAnswersCount() {
      return answers_.size();
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param index The index of the element to return.
     * @return The answers at the given index.
     */
    public java.lang.String getAnswers(int index) {
      return answers_.get(index);
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the answers at the given index.
     */
    public com.google.protobuf.ByteString
        getAnswersBytes(int index) {
      return answers_.getByteString(index);
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param index The index to set the value at.
     * @param value The answers to set.
     * @return This builder for chaining.
     */
    public Builder setAnswers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAnswersIsMutable();
      answers_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param value The answers to add.
     * @return This builder for chaining.
     */
    public Builder addAnswers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAnswersIsMutable();
      answers_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param values The answers to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnswers(
        java.lang.Iterable<java.lang.String> values) {
      ensureAnswersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, answers_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAnswers() {
      answers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The kinds of question the engine answers: "evaluate", "outcomes",
     * "holds", "sensitive", "satisfiable", "sweep", "compute".
     * </pre>
     *
     * <code>repeated string answers = 3 [json_name = "answers"];</code>
     * @param value The bytes of the answers to add.
     * @return This builder for chaining.
     */
    public Builder addAnswersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAnswersIsMutable();
      answers_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList bounds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureBoundsIsMutable() {
      if (!bounds_.isModifiable()) {
        bounds_ = new com.google.protobuf.LazyStringArrayList(bounds_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @return A list containing the bounds.
     */
    public com.google.protobuf.ProtocolStringList
        getBoundsList() {
      bounds_.makeImmutable();
      return bounds_;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @return The count of bounds.
     */
    public int getBoundsCount() {
      return bounds_.size();
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param index The index of the element to return.
     * @return The bounds at the given index.
     */
    public java.lang.String getBounds(int index) {
      return bounds_.get(index);
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the bounds at the given index.
     */
    public com.google.protobuf.ByteString
        getBoundsBytes(int index) {
      return bounds_.getByteString(index);
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param index The index to set the value at.
     * @param value The bounds to set.
     * @return This builder for chaining.
     */
    public Builder setBounds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBoundsIsMutable();
      bounds_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param value The bounds to add.
     * @return This builder for chaining.
     */
    public Builder addBounds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureBoundsIsMutable();
      bounds_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param values The bounds to add.
     * @return This builder for chaining.
     */
    public Builder addAllBounds(
        java.lang.Iterable<java.lang.String> values) {
      ensureBoundsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, bounds_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBounds() {
      bounds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bounds the engine takes, in the order it reports them.
     * </pre>
     *
     * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
     * @param value The bytes of the bounds to add.
     * @return This builder for chaining.
     */
    public Builder addBoundsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureBoundsIsMutable();
      bounds_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object process_ = "";
    /**
     * <pre>
     * The external process the engine needs, empty for one running in-process;
     * `process_found` says where it was found when it was.
     * </pre>
     *
     * <code>string process = 5 [json_name = "process"];</code>
     * @return The process.
     */
    public java.lang.String getProcess() {
      java.lang.Object ref = process_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        process_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The external process the engine needs, empty for one running in-process;
     * `process_found` says where it was found when it was.
     * </pre>
     *
     * <code>string process = 5 [json_name = "process"];</code>
     * @return The bytes for process.
     */
    public com.google.protobuf.ByteString
        getProcessBytes() {
      java.lang.Object ref = process_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        process_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The external process the engine needs, empty for one running in-process;
     * `process_found` says where it was found when it was.
     * </pre>
     *
     * <code>string process = 5 [json_name = "process"];</code>
     * @param value The process to set.
     * @return This builder for chaining.
     */
    public Builder setProcess(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      process_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The external process the engine needs, empty for one running in-process;
     * `process_found` says where it was found when it was.
     * </pre>
     *
     * <code>string process = 5 [json_name = "process"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProcess() {
      process_ = getDefaultInstance().getProcess();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The external process the engine needs, empty for one running in-process;
     * `process_found` says where it was found when it was.
     * </pre>
     *
     * <code>string process = 5 [json_name = "process"];</code>
     * @param value The bytes for process to set.
     * @return This builder for chaining.
     */
    public Builder setProcessBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      process_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object processFound_ = "";
    /**
     * <code>string process_found = 6 [json_name = "processFound"];</code>
     * @return The processFound.
     */
    public java.lang.String getProcessFound() {
      java.lang.Object ref = processFound_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processFound_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string process_found = 6 [json_name = "processFound"];</code>
     * @return The bytes for processFound.
     */
    public com.google.protobuf.ByteString
        getProcessFoundBytes() {
      java.lang.Object ref = processFound_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processFound_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string process_found = 6 [json_name = "processFound"];</code>
     * @param value The processFound to set.
     * @return This builder for chaining.
     */
    public Builder setProcessFound(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      processFound_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string process_found = 6 [json_name = "processFound"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessFound() {
      processFound_ = getDefaultInstance().getProcessFound();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string process_found = 6 [json_name = "processFound"];</code>
     * @param value The bytes for processFound to set.
     * @return This builder for chaining.
     */
    public Builder setProcessFoundBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      processFound_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean ready_ ;
    /**
     * <pre>
     * True when the engine can run: it is served, and it needs no process or its
     * process was found.
     * </pre>
     *
     * <code>bool ready = 7 [json_name = "ready"];</code>
     * @return The ready.
     */
    @java.lang.Override
    public boolean getReady() {
      return ready_;
    }
    /**
     * <pre>
     * True when the engine can run: it is served, and it needs no process or its
     * process was found.
     * </pre>
     *
     * <code>bool ready = 7 [json_name = "ready"];</code>
     * @param value The ready to set.
     * @return This builder for chaining.
     */
    public Builder setReady(boolean value) {

      ready_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True when the engine can run: it is served, and it needs no process or its
     * process was found.
     * </pre>
     *
     * <code>bool ready = 7 [json_name = "ready"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReady() {
      bitField0_ = (bitField0_ & ~0x00000040);
      ready_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object unavailable_ = "";
    /**
     * <pre>
     * Why the engine cannot run, empty when it can.
     * </pre>
     *
     * <code>string unavailable = 8 [json_name = "unavailable"];</code>
     * @return The unavailable.
     */
    public java.lang.String getUnavailable() {
      java.lang.Object ref = unavailable_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unavailable_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Why the engine cannot run, empty when it can.
     * </pre>
     *
     * <code>string unavailable = 8 [json_name = "unavailable"];</code>
     * @return The bytes for unavailable.
     */
    public com.google.protobuf.ByteString
        getUnavailableBytes() {
      java.lang.Object ref = unavailable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unavailable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Why the engine cannot run, empty when it can.
     * </pre>
     *
     * <code>string unavailable = 8 [json_name = "unavailable"];</code>
     * @param value The unavailable to set.
     * @return This builder for chaining.
     */
    public Builder setUnavailable(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unavailable_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why the engine cannot run, empty when it can.
     * </pre>
     *
     * <code>string unavailable = 8 [json_name = "unavailable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUnavailable() {
      unavailable_ = getDefaultInstance().getUnavailable();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why the engine cannot run, empty when it can.
     * </pre>
     *
     * <code>string unavailable = 8 [json_name = "unavailable"];</code>
     * @param value The bytes for unavailable to set.
     * @return This builder for chaining.
     */
    public Builder setUnavailableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unavailable_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object kind_ = "";
    /**
     * <pre>
     * Where the engine comes from: "built-in" for the build's own, else the kind
     * of the manifest entry that registered it: "tool", "engine", "policy" or
     * "sampler". The fields below are empty for a built-in engine.
     * </pre>
     *
     * <code>string kind = 9 [json_name = "kind"];</code>
     * @return The kind.
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Where the engine comes from: "built-in" for the build's own, else the kind
     * of the manifest entry that registered it: "tool", "engine", "policy" or
     * "sampler". The fields below are empty for a built-in engine.
     * </pre>
     *
     * <code>string kind = 9 [json_name = "kind"];</code>
     * @return The bytes for kind.
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Where the engine comes from: "built-in" for the build's own, else the kind
     * of the manifest entry that registered it: "tool", "engine", "policy" or
     * "sampler". The fields below are empty for a built-in engine.
     * </pre>
     *
     * <code>string kind = 9 [json_name = "kind"];</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kind_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the engine comes from: "built-in" for the build's own, else the kind
     * of the manifest entry that registered it: "tool", "engine", "policy" or
     * "sampler". The fields below are empty for a built-in engine.
     * </pre>
     *
     * <code>string kind = 9 [json_name = "kind"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      kind_ = getDefaultInstance().getKind();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Where the engine comes from: "built-in" for the build's own, else the kind
     * of the manifest entry that registered it: "tool", "engine", "policy" or
     * "sampler". The fields below are empty for a built-in engine.
     * </pre>
     *
     * <code>string kind = 9 [json_name = "kind"];</code>
     * @param value The bytes for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kind_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object protocol_ = "";
    /**
     * <pre>
     * How the engine is spoken to: "-" for one built in; for a tool, "object"
     * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
     * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
     * when the reply block reads another format (the format alone when the entry
     * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
     * </pre>
     *
     * <code>string protocol = 10 [json_name = "protocol"];</code>
     * @return The protocol.
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * How the engine is spoken to: "-" for one built in; for a tool, "object"
     * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
     * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
     * when the reply block reads another format (the format alone when the entry
     * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
     * </pre>
     *
     * <code>string protocol = 10 [json_name = "protocol"];</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * How the engine is spoken to: "-" for one built in; for a tool, "object"
     * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
     * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
     * when the reply block reads another format (the format alone when the entry
     * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
     * </pre>
     *
     * <code>string protocol = 10 [json_name = "protocol"];</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      protocol_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the engine is spoken to: "-" for one built in; for a tool, "object"
     * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
     * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
     * when the reply block reads another format (the format alone when the entry
     * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
     * </pre>
     *
     * <code>string protocol = 10 [json_name = "protocol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      protocol_ = getDefaultInstance().getProtocol();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * How the engine is spoken to: "-" for one built in; for a tool, "object"
     * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
     * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
     * when the reply block reads another format (the format alone when the entry
     * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
     * </pre>
     *
     * <code>string protocol = 10 [json_name = "protocol"];</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      protocol_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * The manifest entry the engine was registered from, the command it resolved
     * to and the version the entry declares.
     * </pre>
     *
     * <code>string source = 11 [json_name = "source"];</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The manifest entry the engine was registered from, the command it resolved
     * to and the version the entry declares.
     * </pre>
     *
     * <code>string source = 11 [json_name = "source"];</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The manifest entry the engine was registered from, the command it resolved
     * to and the version the entry declares.
     * </pre>
     *
     * <code>string source = 11 [json_name = "source"];</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The manifest entry the engine was registered from, the command it resolved
     * to and the version the entry declares.
     * </pre>
     *
     * <code>string source = 11 [json_name = "source"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The manifest entry the engine was registered from, the command it resolved
     * to and the version the entry declares.
     * </pre>
     *
     * <code>string source = 11 [json_name = "source"];</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object command_ = "";
    /**
     * <code>string command = 12 [json_name = "command"];</code>
     * @return The command.
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command = 12 [json_name = "command"];</code>
     * @return The bytes for command.
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command = 12 [json_name = "command"];</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      command_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string command = 12 [json_name = "command"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      command_ = getDefaultInstance().getCommand();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string command = 12 [json_name = "command"];</code>
     * @param value The bytes for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      command_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 13 [json_name = "version"];</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 13 [json_name = "version"];</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 13 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 13 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string version = 13 [json_name = "version"];</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private boolean served_ ;
    /**
     * <pre>
     * True when this service runs the engine for a request that reaches it. A
     * manifest engine is listed but not served until the service is started with
     * -serve-external-engines naming it; a request naming one that is not served
     * is FAILED_PRECONDITION.
     * </pre>
     *
     * <code>bool served = 14 [json_name = "served"];</code>
     * @return The served.
     */
    @java.lang.Override
    public boolean getServed() {
      return served_;
    }
    /**
     * <pre>
     * True when this service runs the engine for a request that reaches it. A
     * manifest engine is listed but not served until the service is started with
     * -serve-external-engines naming it; a request naming one that is not served
     * is FAILED_PRECONDITION.
     * </pre>
     *
     * <code>bool served = 14 [json_name = "served"];</code>
     * @param value The served to set.
     * @return This builder for chaining.
     */
    public Builder setServed(boolean value) {

      served_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * True when this service runs the engine for a request that reaches it. A
     * manifest engine is listed but not served until the service is started with
     * -serve-external-engines naming it; a request naming one that is not served
     * is FAILED_PRECONDITION.
     * </pre>
     *
     * <code>bool served = 14 [json_name = "served"];</code>
     * @return This builder for chaining.
     */
    public Builder clearServed() {
      bitField0_ = (bitField0_ & ~0x00002000);
      served_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.EngineInfo)
  }

  // @@protoc_insertion_point(class_scope:sysml.EngineInfo)
  private static final org.openmbee.opensysml.proto.EngineInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.EngineInfo();
  }

  public static org.openmbee.opensysml.proto.EngineInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EngineInfo>
      PARSER = new com.google.protobuf.AbstractParser<EngineInfo>() {
    @java.lang.Override
    public EngineInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EngineInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EngineInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.EngineInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

