// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface EngineInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.EngineInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The engine's name, as a request's `engine` field selects it.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The engine's name, as a request's `engine` field selects it.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The strongest evidence the engine can ever produce, spelled as
   * Verdict.strength is.
   * </pre>
   *
   * <code>string authority = 2 [json_name = "authority"];</code>
   * @return The authority.
   */
  java.lang.String getAuthority();
  /**
   * <pre>
   * The strongest evidence the engine can ever produce, spelled as
   * Verdict.strength is.
   * </pre>
   *
   * <code>string authority = 2 [json_name = "authority"];</code>
   * @return The bytes for authority.
   */
  com.google.protobuf.ByteString
      getAuthorityBytes();

  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @return A list containing the answers.
   */
  java.util.List<java.lang.String>
      getAnswersList();
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @return The count of answers.
   */
  int getAnswersCount();
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @param index The index of the element to return.
   * @return The answers at the given index.
   */
  java.lang.String getAnswers(int index);
  /**
   * <pre>
   * The kinds of question the engine answers: "evaluate", "outcomes",
   * "holds", "sensitive", "satisfiable", "sweep", "compute".
   * </pre>
   *
   * <code>repeated string answers = 3 [json_name = "answers"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the answers at the given index.
   */
  com.google.protobuf.ByteString
      getAnswersBytes(int index);

  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @return A list containing the bounds.
   */
  java.util.List<java.lang.String>
      getBoundsList();
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @return The count of bounds.
   */
  int getBoundsCount();
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @param index The index of the element to return.
   * @return The bounds at the given index.
   */
  java.lang.String getBounds(int index);
  /**
   * <pre>
   * The bounds the engine takes, in the order it reports them.
   * </pre>
   *
   * <code>repeated string bounds = 4 [json_name = "bounds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the bounds at the given index.
   */
  com.google.protobuf.ByteString
      getBoundsBytes(int index);

  /**
   * <pre>
   * The external process the engine needs, empty for one running in-process;
   * `process_found` says where it was found when it was.
   * </pre>
   *
   * <code>string process = 5 [json_name = "process"];</code>
   * @return The process.
   */
  java.lang.String getProcess();
  /**
   * <pre>
   * The external process the engine needs, empty for one running in-process;
   * `process_found` says where it was found when it was.
   * </pre>
   *
   * <code>string process = 5 [json_name = "process"];</code>
   * @return The bytes for process.
   */
  com.google.protobuf.ByteString
      getProcessBytes();

  /**
   * <code>string process_found = 6 [json_name = "processFound"];</code>
   * @return The processFound.
   */
  java.lang.String getProcessFound();
  /**
   * <code>string process_found = 6 [json_name = "processFound"];</code>
   * @return The bytes for processFound.
   */
  com.google.protobuf.ByteString
      getProcessFoundBytes();

  /**
   * <pre>
   * True when the engine can run: it is served, and it needs no process or its
   * process was found.
   * </pre>
   *
   * <code>bool ready = 7 [json_name = "ready"];</code>
   * @return The ready.
   */
  boolean getReady();

  /**
   * <pre>
   * Why the engine cannot run, empty when it can.
   * </pre>
   *
   * <code>string unavailable = 8 [json_name = "unavailable"];</code>
   * @return The unavailable.
   */
  java.lang.String getUnavailable();
  /**
   * <pre>
   * Why the engine cannot run, empty when it can.
   * </pre>
   *
   * <code>string unavailable = 8 [json_name = "unavailable"];</code>
   * @return The bytes for unavailable.
   */
  com.google.protobuf.ByteString
      getUnavailableBytes();

  /**
   * <pre>
   * Where the engine comes from: "built-in" for the build's own, else the kind
   * of the manifest entry that registered it: "tool", "engine", "policy" or
   * "sampler". The fields below are empty for a built-in engine.
   * </pre>
   *
   * <code>string kind = 9 [json_name = "kind"];</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <pre>
   * Where the engine comes from: "built-in" for the build's own, else the kind
   * of the manifest entry that registered it: "tool", "engine", "policy" or
   * "sampler". The fields below are empty for a built-in engine.
   * </pre>
   *
   * <code>string kind = 9 [json_name = "kind"];</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();

  /**
   * <pre>
   * How the engine is spoken to: "-" for one built in; for a tool, "object"
   * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
   * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
   * when the reply block reads another format (the format alone when the entry
   * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
   * </pre>
   *
   * <code>string protocol = 10 [json_name = "protocol"];</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   * How the engine is spoken to: "-" for one built in; for a tool, "object"
   * for the one-JSON-object exchange or "argv+&lt;stdin&gt;" when the entry has an
   * invocation block, with a "/&lt;reply format&gt;" suffix such as "argv+none/csv"
   * when the reply block reads another format (the format alone when the entry
   * has no invocation); "&lt;transport&gt;/&lt;protocol&gt;" for an engine entry.
   * </pre>
   *
   * <code>string protocol = 10 [json_name = "protocol"];</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <pre>
   * The manifest entry the engine was registered from, the command it resolved
   * to and the version the entry declares.
   * </pre>
   *
   * <code>string source = 11 [json_name = "source"];</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * The manifest entry the engine was registered from, the command it resolved
   * to and the version the entry declares.
   * </pre>
   *
   * <code>string source = 11 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string command = 12 [json_name = "command"];</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 12 [json_name = "command"];</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>string version = 13 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 13 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * True when this service runs the engine for a request that reaches it. A
   * manifest engine is listed but not served until the service is started with
   * -serve-external-engines naming it; a request naming one that is not served
   * is FAILED_PRECONDITION.
   * </pre>
   *
   * <code>bool served = 14 [json_name = "served"];</code>
   * @return The served.
   */
  boolean getServed();
}
