// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

@com.google.protobuf.Generated
public interface ParseFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sysml.ParseFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return Whether the filePath field is set.
   */
  boolean hasFilePath();
  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Ignored: the service keys its cache by the source it read, so a repeated
   * parse hits the cache whether or not a client sends this.
   * </pre>
   *
   * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
   * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
   *     See sysml.proto;l=556
   * @return The contentHash.
   */
  @java.lang.Deprecated java.lang.String getContentHash();
  /**
   * <pre>
   * Ignored: the service keys its cache by the source it read, so a repeated
   * parse hits the cache whether or not a client sends this.
   * </pre>
   *
   * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
   * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
   *     See sysml.proto;l=556
   * @return The bytes for contentHash.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getContentHashBytes();

  /**
   * <pre>
   * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * Judge the source as conforming SysML v2: notation no pinned production
   * admits is an error rather than a warning. Part of the cache key, so the two
   * modes never serve each other's diagnostics.
   * </pre>
   *
   * <code>bool strict_conformance = 5 [json_name = "strictConformance"];</code>
   * @return The strictConformance.
   */
  boolean getStrictConformance();

  org.openmbee.opensysml.proto.ParseFileRequest.SourceCase getSourceCase();
}
