// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sysml.proto
// Protobuf Java Version: 4.33.1

package org.openmbee.opensysml.proto;

/**
 * <pre>
 * ParseFileRequest specifies the source to parse
 * </pre>
 *
 * Protobuf type {@code sysml.ParseFileRequest}
 */
@com.google.protobuf.Generated
public final class ParseFileRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sysml.ParseFileRequest)
    ParseFileRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "ParseFileRequest");
  }
  // Use ParseFileRequest.newBuilder() to construct.
  private ParseFileRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ParseFileRequest() {
    contentHash_ = "";
    language_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.openmbee.opensysml.proto.ParseFileRequest.class, org.openmbee.opensysml.proto.ParseFileRequest.Builder.class);
  }

  private int sourceCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object source_;
  public enum SourceCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE_PATH(1),
    CONTENT(2),
    SOURCE_NOT_SET(0);
    private final int value;
    private SourceCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SourceCase valueOf(int value) {
      return forNumber(value);
    }

    public static SourceCase forNumber(int value) {
      switch (value) {
        case 1: return FILE_PATH;
        case 2: return CONTENT;
        case 0: return SOURCE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SourceCase
  getSourceCase() {
    return SourceCase.forNumber(
        sourceCase_);
  }

  public static final int FILE_PATH_FIELD_NUMBER = 1;
  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return Whether the filePath field is set.
   */
  public boolean hasFilePath() {
    return sourceCase_ == 1;
  }
  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return The filePath.
   */
  public java.lang.String getFilePath() {
    java.lang.Object ref = "";
    if (sourceCase_ == 1) {
      ref = source_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (sourceCase_ == 1) {
        source_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string file_path = 1 [json_name = "filePath"];</code>
   * @return The bytes for filePath.
   */
  public com.google.protobuf.ByteString
      getFilePathBytes() {
    java.lang.Object ref = "";
    if (sourceCase_ == 1) {
      ref = source_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (sourceCase_ == 1) {
        source_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return Whether the content field is set.
   */
  public boolean hasContent() {
    return sourceCase_ == 2;
  }
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The content.
   */
  public java.lang.String getContent() {
    java.lang.Object ref = "";
    if (sourceCase_ == 2) {
      ref = source_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (sourceCase_ == 2) {
        source_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string content = 2 [json_name = "content"];</code>
   * @return The bytes for content.
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = "";
    if (sourceCase_ == 2) {
      ref = source_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (sourceCase_ == 2) {
        source_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_HASH_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentHash_ = "";
  /**
   * <pre>
   * Ignored: the service keys its cache by the source it read, so a repeated
   * parse hits the cache whether or not a client sends this.
   * </pre>
   *
   * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
   * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
   *     See sysml.proto;l=556
   * @return The contentHash.
   */
  @java.lang.Override
  @java.lang.Deprecated public java.lang.String getContentHash() {
    java.lang.Object ref = contentHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Ignored: the service keys its cache by the source it read, so a repeated
   * parse hits the cache whether or not a client sends this.
   * </pre>
   *
   * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
   * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
   *     See sysml.proto;l=556
   * @return The bytes for contentHash.
   */
  @java.lang.Override
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getContentHashBytes() {
    java.lang.Object ref = contentHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <pre>
   * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
   * </pre>
   *
   * <code>string language = 4 [json_name = "language"];</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRICT_CONFORMANCE_FIELD_NUMBER = 5;
  private boolean strictConformance_ = false;
  /**
   * <pre>
   * Judge the source as conforming SysML v2: notation no pinned production
   * admits is an error rather than a warning. Part of the cache key, so the two
   * modes never serve each other's diagnostics.
   * </pre>
   *
   * <code>bool strict_conformance = 5 [json_name = "strictConformance"];</code>
   * @return The strictConformance.
   */
  @java.lang.Override
  public boolean getStrictConformance() {
    return strictConformance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sourceCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, source_);
    }
    if (sourceCase_ == 2) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, contentHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, language_);
    }
    if (strictConformance_ != false) {
      output.writeBool(5, strictConformance_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sourceCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, source_);
    }
    if (sourceCase_ == 2) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, source_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, contentHash_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, language_);
    }
    if (strictConformance_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, strictConformance_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.openmbee.opensysml.proto.ParseFileRequest)) {
      return super.equals(obj);
    }
    org.openmbee.opensysml.proto.ParseFileRequest other = (org.openmbee.opensysml.proto.ParseFileRequest) obj;

    if (!getContentHash()
        .equals(other.getContentHash())) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (getStrictConformance()
        != other.getStrictConformance()) return false;
    if (!getSourceCase().equals(other.getSourceCase())) return false;
    switch (sourceCase_) {
      case 1:
        if (!getFilePath()
            .equals(other.getFilePath())) return false;
        break;
      case 2:
        if (!getContent()
            .equals(other.getContent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTENT_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getContentHash().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + STRICT_CONFORMANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStrictConformance());
    switch (sourceCase_) {
      case 1:
        hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getFilePath().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.openmbee.opensysml.proto.ParseFileRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.openmbee.opensysml.proto.ParseFileRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.openmbee.opensysml.proto.ParseFileRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.openmbee.opensysml.proto.ParseFileRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ParseFileRequest specifies the source to parse
   * </pre>
   *
   * Protobuf type {@code sysml.ParseFileRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sysml.ParseFileRequest)
      org.openmbee.opensysml.proto.ParseFileRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openmbee.opensysml.proto.ParseFileRequest.class, org.openmbee.opensysml.proto.ParseFileRequest.Builder.class);
    }

    // Construct using org.openmbee.opensysml.proto.ParseFileRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contentHash_ = "";
      language_ = "";
      strictConformance_ = false;
      sourceCase_ = 0;
      source_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.openmbee.opensysml.proto.Sysml.internal_static_sysml_ParseFileRequest_descriptor;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileRequest getDefaultInstanceForType() {
      return org.openmbee.opensysml.proto.ParseFileRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileRequest build() {
      org.openmbee.opensysml.proto.ParseFileRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.openmbee.opensysml.proto.ParseFileRequest buildPartial() {
      org.openmbee.opensysml.proto.ParseFileRequest result = new org.openmbee.opensysml.proto.ParseFileRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(org.openmbee.opensysml.proto.ParseFileRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.contentHash_ = contentHash_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.strictConformance_ = strictConformance_;
      }
    }

    private void buildPartialOneofs(org.openmbee.opensysml.proto.ParseFileRequest result) {
      result.sourceCase_ = sourceCase_;
      result.source_ = this.source_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.openmbee.opensysml.proto.ParseFileRequest) {
        return mergeFrom((org.openmbee.opensysml.proto.ParseFileRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.openmbee.opensysml.proto.ParseFileRequest other) {
      if (other == org.openmbee.opensysml.proto.ParseFileRequest.getDefaultInstance()) return this;
      if (!other.getContentHash().isEmpty()) {
        contentHash_ = other.contentHash_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getStrictConformance() != false) {
        setStrictConformance(other.getStrictConformance());
      }
      switch (other.getSourceCase()) {
        case FILE_PATH: {
          sourceCase_ = 1;
          source_ = other.source_;
          onChanged();
          break;
        }
        case CONTENT: {
          sourceCase_ = 2;
          source_ = other.source_;
          onChanged();
          break;
        }
        case SOURCE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              sourceCase_ = 1;
              source_ = s;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              sourceCase_ = 2;
              source_ = s;
              break;
            } // case 18
            case 26: {
              contentHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              strictConformance_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int sourceCase_ = 0;
    private java.lang.Object source_;
    public SourceCase
        getSourceCase() {
      return SourceCase.forNumber(
          sourceCase_);
    }

    public Builder clearSource() {
      sourceCase_ = 0;
      source_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @return Whether the filePath field is set.
     */
    @java.lang.Override
    public boolean hasFilePath() {
      return sourceCase_ == 1;
    }
    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      java.lang.Object ref = "";
      if (sourceCase_ == 1) {
        ref = source_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (sourceCase_ == 1) {
          source_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = "";
      if (sourceCase_ == 1) {
        ref = source_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (sourceCase_ == 1) {
          source_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @param value The filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceCase_ = 1;
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePath() {
      if (sourceCase_ == 1) {
        sourceCase_ = 0;
        source_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string file_path = 1 [json_name = "filePath"];</code>
     * @param value The bytes for filePath to set.
     * @return This builder for chaining.
     */
    public Builder setFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceCase_ = 1;
      source_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @return Whether the content field is set.
     */
    @java.lang.Override
    public boolean hasContent() {
      return sourceCase_ == 2;
    }
    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = "";
      if (sourceCase_ == 2) {
        ref = source_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (sourceCase_ == 2) {
          source_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = "";
      if (sourceCase_ == 2) {
        ref = source_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (sourceCase_ == 2) {
          source_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceCase_ = 2;
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      if (sourceCase_ == 2) {
        sourceCase_ = 0;
        source_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string content = 2 [json_name = "content"];</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceCase_ = 2;
      source_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contentHash_ = "";
    /**
     * <pre>
     * Ignored: the service keys its cache by the source it read, so a repeated
     * parse hits the cache whether or not a client sends this.
     * </pre>
     *
     * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
     * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
     *     See sysml.proto;l=556
     * @return The contentHash.
     */
    @java.lang.Deprecated public java.lang.String getContentHash() {
      java.lang.Object ref = contentHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Ignored: the service keys its cache by the source it read, so a repeated
     * parse hits the cache whether or not a client sends this.
     * </pre>
     *
     * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
     * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
     *     See sysml.proto;l=556
     * @return The bytes for contentHash.
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getContentHashBytes() {
      java.lang.Object ref = contentHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Ignored: the service keys its cache by the source it read, so a repeated
     * parse hits the cache whether or not a client sends this.
     * </pre>
     *
     * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
     * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
     *     See sysml.proto;l=556
     * @param value The contentHash to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setContentHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentHash_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ignored: the service keys its cache by the source it read, so a repeated
     * parse hits the cache whether or not a client sends this.
     * </pre>
     *
     * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
     * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
     *     See sysml.proto;l=556
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearContentHash() {
      contentHash_ = getDefaultInstance().getContentHash();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ignored: the service keys its cache by the source it read, so a repeated
     * parse hits the cache whether or not a client sends this.
     * </pre>
     *
     * <code>string content_hash = 3 [json_name = "contentHash", deprecated = true];</code>
     * @deprecated sysml.ParseFileRequest.content_hash is deprecated.
     *     See sysml.proto;l=556
     * @param value The bytes for contentHash to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setContentHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentHash_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <pre>
     * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Language for inline content: "sysml" or "kerml". Empty defaults to SysML.
     * </pre>
     *
     * <code>string language = 4 [json_name = "language"];</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean strictConformance_ ;
    /**
     * <pre>
     * Judge the source as conforming SysML v2: notation no pinned production
     * admits is an error rather than a warning. Part of the cache key, so the two
     * modes never serve each other's diagnostics.
     * </pre>
     *
     * <code>bool strict_conformance = 5 [json_name = "strictConformance"];</code>
     * @return The strictConformance.
     */
    @java.lang.Override
    public boolean getStrictConformance() {
      return strictConformance_;
    }
    /**
     * <pre>
     * Judge the source as conforming SysML v2: notation no pinned production
     * admits is an error rather than a warning. Part of the cache key, so the two
     * modes never serve each other's diagnostics.
     * </pre>
     *
     * <code>bool strict_conformance = 5 [json_name = "strictConformance"];</code>
     * @param value The strictConformance to set.
     * @return This builder for chaining.
     */
    public Builder setStrictConformance(boolean value) {

      strictConformance_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Judge the source as conforming SysML v2: notation no pinned production
     * admits is an error rather than a warning. Part of the cache key, so the two
     * modes never serve each other's diagnostics.
     * </pre>
     *
     * <code>bool strict_conformance = 5 [json_name = "strictConformance"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStrictConformance() {
      bitField0_ = (bitField0_ & ~0x00000010);
      strictConformance_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sysml.ParseFileRequest)
  }

  // @@protoc_insertion_point(class_scope:sysml.ParseFileRequest)
  private static final org.openmbee.opensysml.proto.ParseFileRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.openmbee.opensysml.proto.ParseFileRequest();
  }

  public static org.openmbee.opensysml.proto.ParseFileRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseFileRequest>
      PARSER = new com.google.protobuf.AbstractParser<ParseFileRequest>() {
    @java.lang.Override
    public ParseFileRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseFileRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseFileRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.openmbee.opensysml.proto.ParseFileRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

